import {createRequire} from 'node:module';
import {readFileSync,mkdirSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {extname,resolve,sep} from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const project=fileURLToPath(new URL('../',import.meta.url));
process.chdir(project);
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const mime={'.html':'text/html; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.ttf':'font/ttf','.txt':'text/plain; charset=utf-8'};
const root=resolve(project);let legacyPwa=false;
const server=createServer(async(request,response)=>{
 try{
  const pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname),file=resolve(root,'.'+(pathname==='/'?'/index.html':pathname));
  if(file!==root&&!file.startsWith(root+sep)){response.writeHead(403).end();return;}
  let body=await readFile(file);if(legacyPwa&&['/sw.js','/config.mjs'].includes(pathname))body=Buffer.from(body.toString('utf8').replaceAll('4.0.1','4.0.0'));
  response.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream'});response.end(body);
 }catch(_){response.writeHead(404).end();}
});
await new Promise((done,fail)=>{server.once('error',fail);server.listen(8080,'127.0.0.1',done);});
process.on('exit',()=>server.close());
const browser=await chromium.launch({...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox'],headless:true});
mkdirSync('test-output',{recursive:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
let fixtureScenario=false,cardScenario=false,failCardSave=false,cardSaves=[],combineBootstrap=true,failBootstrap=false,omitPortrait=false;
const apiCalls=[],apiRequests=[];
let portraitGate=null;
const portraitB64=readFileSync('assets/football.jpg').toString('base64');
const players=[{jugador_id:'card1',nom:'Jugador de prova',dorsal:10,posicio:'Migcampista',te_retrat:true,retrat_version:'portrait1',actualitzat_at:'2026-10-06T10:00:00Z'},{jugador_id:'card2',nom:'Un nom llarg de prova',dorsal:1,posicio:'Porter',te_retrat:false,actualitzat_at:''},{jugador_id:'card3',nom:'Prova',dorsal:7,posicio:'Davanter',te_retrat:false,actualitzat_at:''}];
const realCalendar=JSON.parse(readFileSync('tests/fixtures/calendar-2026-27.json','utf8'));
let privacy=false,role='admin',empty=false,failUpload=false,uploads=[],revoked=false,renewSession=false,renewalToken='renewed-test-token',loginToken='synthetic-test-token',delayedUnauthorized=null,delayedPhoto=null,delayedRedeem=null,delayedAccept=null,delayedRenewals=[];
const users=[{telefon:'+34999000123',nom:'Família de prova',rol:'admin',actiu:true,privacitat_acceptada:false,invitacio:null}];
const m={partit_id:'m1',data:'2026-10-10',hora:'10:00',jornada:1,local:'CF VILAJUÏGA',visitant:'Rival de prova',camp_nom:'Camp de prova',camp_adreca:'Adreça de prova',camp_lat:'',camp_lng:'',estat:'pendent',gols_local:'',gols_visitant:'',cronica:'',actualitzat_at:'2026-10-01T10:00:00Z'};
const photo={foto_id:'00000000-0000-4000-8000-000000000001',partit_id:'m1',peu:'Foto de prova',pujat_per_nom:'Família de prova',pujat_at:'2026-10-01T10:00:00Z',no_mostrar:false,bloquejada:false};
const b64=readFileSync('assets/football.jpg').toString('base64');
const bootstrap=()=>({user:{nom:'Família de prova',rol:role,privacyAccepted:privacy},config:{equip_nom:'CF VILAJUÏGA',temporada:'2026/27',privacy_version:'1'},partits:fixtureScenario?realCalendar:empty?[]:[m],jugadors:cardScenario?players.filter(j=>!omitPortrait||j.jugador_id!=='card1'):[],...(cardScenario?{features:{player_cards:true,fresh_permissions:true}}:{}),estadistiques:{PJ:0,V:0,E:0,D:0,GF:0,GC:0,DG:0}});
await context.route('https://script.google.com/**',async route=>{
 const p=JSON.parse(route.request().postData()||'{}');apiCalls.push(p.action);apiRequests.push(p);let data;
 if(delayedRedeem&&p.action==='redeemInvite'){const gate=delayedRedeem;delayedRedeem=null;gate.started();await gate.wait;if(gate.error){await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'BUSY',message:gate.error}})});return;}}
 if(delayedAccept&&p.action==='acceptPrivacy'){const gate=delayedAccept;delayedAccept=null;gate.started();await gate.wait;if(gate.error){await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'BUSY',message:gate.error}})});return;}}
 if(delayedUnauthorized&&p.action==='bootstrap'){const gate=delayedUnauthorized;delayedUnauthorized=null;gate.started();await gate.wait;await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'UNAUTHORIZED',message:'Resposta antiga de prova'}})});return;}
 if(delayedPhoto&&p.action==='getPhoto'){const gate=delayedPhoto;delayedPhoto=null;gate.started();await gate.wait;await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,data:{base64:b64,filename:'prova.jpg'}})});return;}
 if(delayedRenewals.length&&p.action==='bootstrap'){const gate=delayedRenewals.shift();gate.started();await gate.wait;await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,data:{...bootstrap(),renewed:{token:gate.token,expiresAt:'2099-12-31T00:00:00Z'}}})});return;}
 if((revoked||failBootstrap)&&p.action==='bootstrap'){await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:false,error:{code:revoked?'UNAUTHORIZED':'INTERNAL_ERROR',message:'Error sintètic de prova'}})});return;}
 switch(p.action){
 case 'redeemInvite':data={token:loginToken,expiresAt:'2099-01-01T00:00:00Z',user:bootstrap().user,privacy:{text:'Compromís sintètic de prova.',version:'1'},...(combineBootstrap&&privacy&&p.include_bootstrap?{bootstrap:bootstrap()}: {})};break;
 case 'acceptPrivacy':privacy=true;data={accepted:true,...(combineBootstrap&&p.include_bootstrap?{bootstrap:bootstrap()}: {})};break;
 case 'bootstrap':data={...bootstrap(),...(renewSession?{renewed:{token:renewalToken,expiresAt:'2099-12-31T00:00:00Z'}}:{})};break;
 case 'listPhotos':data={fotos:[photo],nextCursor:null};break;
 case 'getThumbnails':data={items:[{foto_id:photo.foto_id,ok:true,base64:b64}]};break;
 case 'getPhoto':case 'downloadPhoto':data={base64:b64,filename:'prova.jpg'};break;
 case 'updateResult':Object.assign(m,{estat:p.estat,gols_local:p.gols_local,gols_visitant:p.gols_visitant,actualitzat_at:'2026-10-06T10:00:00Z'});data={partit:m};break;
 case 'updateChronicle':m.cronica=p.cronica;data={partit:m};break;
 case 'getPlayerPortraits':if(portraitGate)await portraitGate;data={items:p.jugador_ids.map(id=>({ok:true,jugador_id:id,retrat_version:players.find(j=>j.jugador_id===id).retrat_version,base64:portraitB64}))};break;
 case 'savePlayer':cardSaves.push(p);if(failCardSave){failCardSave=false;await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'BUSY',message:'Error sintètic de prova'}})});return;}const oldPlayer=players.find(j=>j.jugador_id===p.jugador_id);const player={...(oldPlayer||{}),jugador_id:p.jugador_id,nom:p.nom,dorsal:p.dorsal,posicio:p.posicio,te_retrat:!!p.photo_base64||!!oldPlayer?.te_retrat,retrat_version:p.foto_id||oldPlayer?.retrat_version,actualitzat_at:'2026-10-06T12:00:00Z'};if(oldPlayer)Object.assign(oldPlayer,player);else players.push(player);data={jugador:player};break;
 case 'listUsers':data={usuaris:users};break;
 case 'createInvite':users[0].invitacio={estat:'pendent',caduca_at:'2099-01-02T12:00:00Z'};data={invite_id:'invite1',telefon:users[0].telefon,nom:users[0].nom,codi:'1234',caduca_at:users[0].invitacio.caduca_at};break;
 case 'saveUser':data={ok:true};break;
 case 'revokeSessions':data={ok:true};break;
 case 'uploadPhoto':uploads.push(p);if(failUpload){failUpload=false;await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'BUSY',message:'Error de prova'}})});return;}data={foto:photo};break;
 case 'hidePhoto':photo.no_mostrar=true;photo.bloquejada=true;data={foto:photo};break;
 case 'showPhoto':photo.no_mostrar=false;photo.bloquejada=false;data={foto:photo};break;
 case 'deletePhoto':data={deleted:true};break;
 case 'logout':data={loggedOut:true};break;
 default:throw new Error('Unexpected action '+p.action);
 }
 await route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({ok:true,data})});
});
async function gateNextImagePreparation(tab){
 await tab.evaluate(()=>{
  const originalBitmap=window.createImageBitmap.bind(window),originalFetch=window.fetch.bind(window);let release;
  window.__imagePreparationStarted=false;window.__imagePreparationCompleted=false;window.__imageWrites=[];
  const held=new Promise(resolve=>release=resolve);window.__releaseImagePreparation=release;
  window.createImageBitmap=async(...args)=>{window.__imagePreparationStarted=true;await held;const bitmap=await originalBitmap(...args),close=bitmap.close.bind(bitmap);bitmap.close=()=>{close();window.__imagePreparationCompleted=true;};window.createImageBitmap=originalBitmap;return bitmap;};
  window.fetch=(...args)=>{try{const payload=JSON.parse(args[1]?.body||'{}');if(['uploadPhoto','savePlayer'].includes(payload.action))window.__imageWrites.push(payload);}catch{}return originalFetch(...args);};
  window.__restoreImageFetch=()=>window.fetch=originalFetch;
 });
}
async function finishImagePreparation(tab){await tab.evaluate(()=>window.__releaseImagePreparation());await tab.waitForFunction(()=>window.__imagePreparationCompleted);await tab.evaluate(()=>new Promise(resolve=>queueMicrotask(()=>queueMicrotask(resolve))));await tab.evaluate(()=>window.__restoreImageFetch());}
function holdRenewal(token){let release,markStarted;const started=new Promise(resolve=>markStarted=resolve),wait=new Promise(resolve=>release=resolve);delayedRenewals.push({token,wait,started:markStarted});return {started,release};}
await page.goto('http://127.0.0.1:8080/');await page.locator('#login-phone').waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'test-output/login-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-output/login-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile login overflow');
await page.locator('#login-phone').fill('999000123');await page.locator('#login-code').fill('1234');await page.locator('#login-form [type=submit]').click();await page.locator('#privacy-form').waitFor();
assert.equal(await page.evaluate(()=>Object.keys(localStorage).length),0,'token stored before consent');
let releaseChangedAccountAccept,markChangedAccountAcceptStarted;const changedAccountAcceptStarted=new Promise(resolve=>markChangedAccountAcceptStarted=resolve);delayedAccept={wait:new Promise(resolve=>releaseChangedAccountAccept=resolve),started:markChangedAccountAcceptStarted};const changedAccountAcceptResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='acceptPrivacy');await page.locator('[name=accepted]').check();await page.locator('#privacy-form [type=submit]').click();await changedAccountAcceptStarted;await page.evaluate(()=>localStorage.setItem('cfv:v3:'+new URL('.',location.href).pathname+':session',JSON.stringify({token:'external-privacy-token',expiresAt:'2099-01-01T00:00:00Z',cacheKey:'external-privacy-cache'})));releaseChangedAccountAccept();await changedAccountAcceptResponse;await page.locator('#login-form').waitFor();assert.equal(await page.evaluate(()=>Object.values(localStorage).some(value=>value.includes('external-privacy-cache'))),true,'an old privacy response must not replace a different shared account');await page.evaluate(()=>Object.keys(localStorage).filter(key=>key.endsWith(':session')).forEach(key=>localStorage.removeItem(key)));privacy=false;await page.reload();await page.locator('#login-phone').fill('999000123');await page.locator('#login-code').fill('1234');await page.locator('#login-form [type=submit]').click();await page.locator('#privacy-form').waitFor();
let releaseAccept,markAcceptStarted;const acceptStarted=new Promise(resolve=>markAcceptStarted=resolve);delayedAccept={wait:new Promise(resolve=>releaseAccept=resolve),started:markAcceptStarted,error:'Error antic d’acceptació'};const staleAcceptResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='acceptPrivacy');await page.locator('[name=accepted]').check();await page.locator('#privacy-form [type=submit]').click();await acceptStarted;
await page.locator('[name=accepted]').check();const currentAcceptResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='acceptPrivacy');await page.evaluate(()=>document.querySelector('#privacy-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await currentAcceptResponse;await page.locator('.hero').waitFor();releaseAccept();await staleAcceptResponse;await page.locator('[data-action=refresh]:enabled').waitFor();assert.equal(await page.locator('.error-panel').count(),0,'a late privacy error must not alter a later successful attempt');
assert.deepEqual(apiCalls,['redeemInvite','acceptPrivacy','redeemInvite','acceptPrivacy','acceptPrivacy'],'privacy races must not add a bootstrap request');
await page.screenshot({path:'test-output/home-mobile-test.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile home overflow');
await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'test-output/home-desktop-test.png',fullPage:true});
await page.locator('.sidebar [data-view=families]').click();await page.locator('.family-card').waitFor();await page.locator('[data-action=invite-user]').click();assert.equal(await page.locator('.invite-result strong').textContent(),'1234');assert.match(await page.locator('a[href^="https://wa.me/"]').getAttribute('href'),/1234/);await page.locator('[data-action=close]').click();await page.locator('.sidebar [data-view=home]').click();
const secondPage=await context.newPage();secondPage.on('pageerror',e=>errors.push(e.message));await secondPage.goto('http://127.0.0.1:8080/');await secondPage.locator('.hero').waitFor();
await secondPage.evaluate(()=>{window.__sessionStorageEvents=[];window.addEventListener('storage',event=>{if(event.key?.endsWith(':session'))window.__sessionStorageEvents.push(event.newValue);});});
for(const round of [{tokens:['parallel-a','parallel-b'],release:[1,0],expected:'parallel-b'},{tokens:['parallel-c','parallel-d'],release:[0,1],expected:'parallel-c'}]){
 const first=holdRenewal(round.tokens[0]),second=holdRenewal(round.tokens[1]);
 const firstResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await page.locator('[data-action=refresh]').click();await first.started;
 const secondResponse=secondPage.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await secondPage.locator('[data-action=refresh]').click();await second.started;
 const held=[first,second],responses=[firstResponse,secondResponse];held[round.release[0]].release();await responses[round.release[0]];held[round.release[1]].release();await responses[round.release[1]];
 for(const tab of [page,secondPage]){await tab.locator('[data-action=refresh]:enabled').waitFor();await tab.waitForFunction(token=>Object.values(localStorage).some(value=>value.includes(token)),round.expected);assert.equal(await tab.locator('.hero').count(),1,'simultaneous renewals must keep both tabs authenticated');}
 const verificationStart=apiRequests.length;const verifyFirst=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap'),verifySecond=secondPage.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await Promise.all([page.locator('[data-action=refresh]').click(),secondPage.locator('[data-action=refresh]').click(),verifyFirst,verifySecond]);assert.deepEqual(apiRequests.slice(verificationStart).filter(request=>request.action==='bootstrap').map(request=>request.token).sort(),[round.expected,round.expected],'both tabs must use the same surviving renewed token');
}
renewSession=true;const renewalResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await page.locator('[data-action=refresh]').click();await renewalResponse;renewSession=false;
await secondPage.waitForFunction(()=>window.__sessionStorageEvents.length>0);await secondPage.waitForTimeout(100);
for(const tab of [page,secondPage]){assert.equal(await tab.evaluate(()=>Object.values(localStorage).some(value=>value.includes('renewed-test-token'))),true,'a legitimate renewal must remain stored in every tab');assert.equal(await tab.locator('.hero').count(),1,'a legitimate renewal must keep every tab authenticated');}
const sessionKey=await page.evaluate(()=>Object.keys(localStorage).find(key=>key.endsWith(':session'))),renewedSession=await page.evaluate(key=>localStorage.getItem(key),sessionKey);
await secondPage.evaluate(({key,current})=>window.dispatchEvent(new StorageEvent('storage',{key,oldValue:current,newValue:null,storageArea:localStorage,url:location.href})),{key:sessionKey,current:renewedSession});
await secondPage.waitForTimeout(50);assert.equal(await secondPage.locator('.hero').count(),1,'an obsolete removal event cannot clear a newer shared session');assert.equal(await secondPage.evaluate(key=>localStorage.getItem(key),sessionKey),renewedSession);

const gapOriginalSession=await page.evaluate(key=>localStorage.getItem(key),sessionKey),gapRenewal=holdRenewal('must-not-overwrite-external-session'),gapResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await page.locator('[data-action=refresh]').click();await gapRenewal.started;await page.evaluate(key=>{const session=JSON.parse(localStorage.getItem(key));localStorage.setItem(key,JSON.stringify({...session,token:'external-gap-token',cacheKey:'external-gap-cache'}));},sessionKey);gapRenewal.release();await gapResponse;assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).cacheKey,sessionKey),'external-gap-cache','a renewal response must not overwrite a different shared session before its storage event arrives');
const externalGapRaw=await page.evaluate(key=>localStorage.getItem(key),sessionKey);await page.evaluate(({key,raw})=>window.dispatchEvent(new StorageEvent('storage',{key,oldValue:null,newValue:raw,storageArea:localStorage,url:location.href})),{key:sessionKey,raw:externalGapRaw});await page.locator('#login-form').waitFor();await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:sessionKey,raw:gapOriginalSession});await Promise.all([page.reload(),secondPage.reload()]);await Promise.all([page.locator('.hero').waitFor(),secondPage.locator('.hero').waitFor()]);

let releaseGapUnauthorized,markGapUnauthorizedStarted;const gapUnauthorizedStarted=new Promise(resolve=>markGapUnauthorizedStarted=resolve);delayedUnauthorized={wait:new Promise(resolve=>releaseGapUnauthorized=resolve),started:markGapUnauthorizedStarted};const gapUnauthorizedResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await page.locator('[data-action=refresh]').click();await gapUnauthorizedStarted;const newerSharedRaw=await page.evaluate(key=>{const session=JSON.parse(localStorage.getItem(key)),raw=JSON.stringify({...session,token:'same-cache-newer-token'});localStorage.setItem(key,raw);return raw;},sessionKey);releaseGapUnauthorized();await gapUnauthorizedResponse;assert.equal(await page.evaluate(key=>{const raw=localStorage.getItem(key);return raw&&JSON.parse(raw).token;},sessionKey),'same-cache-newer-token','an unauthorized response for the old token must not clear a newer shared token before its storage event');await page.evaluate(({key,raw})=>window.dispatchEvent(new StorageEvent('storage',{key,oldValue:null,newValue:raw,storageArea:localStorage,url:location.href})),{key:sessionKey,raw:newerSharedRaw});await Promise.all([page.reload(),secondPage.reload()]);await Promise.all([page.locator('.hero').waitFor(),secondPage.locator('.hero').waitFor()]);

let releaseUnauthorized,markUnauthorizedStarted;const unauthorizedStarted=new Promise(resolve=>markUnauthorizedStarted=resolve);
delayedUnauthorized={wait:new Promise(resolve=>releaseUnauthorized=resolve),started:markUnauthorizedStarted};
const staleUnauthorizedResponse=secondPage.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await secondPage.locator('[data-action=refresh]').click();await unauthorizedStarted;
renewalToken='newer-test-token';renewSession=true;const newerRenewalResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await page.locator('[data-action=refresh]').click();await newerRenewalResponse;renewSession=false;
await secondPage.waitForFunction(()=>Object.values(localStorage).some(value=>value.includes('newer-test-token')));releaseUnauthorized();await staleUnauthorizedResponse;await secondPage.waitForTimeout(50);
for(const tab of [page,secondPage]){assert.equal(await tab.locator('.hero').count(),1,'an old unauthorized response cannot clear a renewed session');assert.equal(await tab.evaluate(()=>Object.values(localStorage).some(value=>value.includes('newer-test-token'))),true);}

await secondPage.locator('.sidebar [data-view=photos]').click();await secondPage.locator('[data-thumb]:visible').waitFor();
let releasePhoto,markPhotoStarted;const photoStarted=new Promise(resolve=>markPhotoStarted=resolve);delayedPhoto={wait:new Promise(resolve=>releasePhoto=resolve),started:markPhotoStarted};
const stalePhotoResponse=secondPage.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='getPhoto');await secondPage.locator('[data-action=photo]').click();await photoStarted;
const previousSession=await page.evaluate(key=>{const raw=localStorage.getItem(key),session=JSON.parse(raw);return {raw,cacheKey:session.cacheKey,dataKey:Object.keys(localStorage).find(candidate=>candidate.endsWith('data:'+session.cacheKey))};},sessionKey);
await page.evaluate(key=>{const session=JSON.parse(localStorage.getItem(key));localStorage.setItem(key,JSON.stringify({...session,token:'different-user-token',cacheKey:'different-user-cache'}));},sessionKey);
await secondPage.locator('#login-form').waitFor();assert.equal(await secondPage.evaluate(()=>document.getElementById('modal').open),false,'a changed account closes private dialogs');assert.equal(await secondPage.evaluate(()=>document.querySelectorAll('img[src^="blob:"]').length),0,'a changed account removes private blob images');assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).token,sessionKey),'different-user-token','the old tab must not delete the new shared session');assert.equal(await page.evaluate(key=>key?localStorage.getItem(key):null,previousSession.dataKey),null,'the previous account snapshot must be removed');
releasePhoto();await stalePhotoResponse;await secondPage.waitForTimeout(50);assert.equal(await secondPage.locator('#login-form').count(),1,'a late private response cannot restore the previous account');assert.equal(await secondPage.evaluate(()=>document.querySelectorAll('img[src^="blob:"]').length),0);
await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:sessionKey,raw:previousSession.raw});await secondPage.reload();await secondPage.locator('.hero').waitFor();

await secondPage.locator('.sidebar [data-view=photos]').click();await secondPage.locator('[data-action=upload]').first().click();await secondPage.locator('#upload-files').setInputFiles({name:'renovacio.jpg',mimeType:'image/jpeg',buffer:readFileSync('assets/football.jpg')});await secondPage.locator('#photo-no-players').check();await gateNextImagePreparation(secondPage);await secondPage.locator('#upload-form [type=submit]').click();await secondPage.waitForFunction(()=>window.__imagePreparationStarted);
renewalToken='image-renewal-token';renewSession=true;const imageRenewalResponse=page.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='bootstrap');await page.locator('[data-action=refresh]').click();await imageRenewalResponse;renewSession=false;await secondPage.waitForFunction(()=>Object.values(localStorage).some(value=>value.includes('image-renewal-token')));await finishImagePreparation(secondPage);await secondPage.locator('.queue-item.done').waitFor();assert.equal(uploads.at(-1)?.token,'image-renewal-token','an upload must continue with a legitimately renewed token from the same session');await secondPage.locator('[data-action=close]').first().click();uploads=[];previousSession.raw=await page.evaluate(key=>localStorage.getItem(key),sessionKey);

await secondPage.locator('.sidebar [data-view=photos]').click();await secondPage.locator('[data-action=upload]').first().click();await secondPage.locator('#upload-files').setInputFiles({name:'sessio-a.jpg',mimeType:'image/jpeg',buffer:readFileSync('assets/football.jpg')});await secondPage.locator('#photo-no-players').check();await gateNextImagePreparation(secondPage);await secondPage.locator('#upload-form [type=submit]').click();await secondPage.waitForFunction(()=>window.__imagePreparationStarted);
await page.evaluate(key=>{const session=JSON.parse(localStorage.getItem(key));localStorage.setItem(key,JSON.stringify({...session,token:'account-b-seed-token',cacheKey:'account-b-seed-cache'}));},sessionKey);await secondPage.locator('#login-form').waitFor();loginToken='account-b-token';await secondPage.locator('#login-phone').fill('999000123');await secondPage.locator('#login-code').fill('1234');await secondPage.locator('#login-form [type=submit]').click();await secondPage.locator('.hero').waitFor();await finishImagePreparation(secondPage);
assert.equal(await secondPage.evaluate(()=>window.__imageWrites.some(payload=>payload.action==='uploadPhoto'&&payload.token==='account-b-token')),false,'a gallery upload prepared by account A must never use account B credentials');
loginToken='synthetic-test-token';await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:sessionKey,raw:previousSession.raw});await Promise.all([page.reload(),secondPage.reload()]);await Promise.all([page.locator('.hero').waitFor(),secondPage.locator('.hero').waitFor()]);

await page.locator('[data-action=match]').first().click();await page.locator('[data-action=edit-match]').click();await page.selectOption('#match-status','jugat');await page.fill('#gols-local','2');await page.fill('#gols-visitant','1');await page.locator('#edit-form [type=submit]').click();await page.locator('.detail-score').filter({hasText:'2 : 1'}).waitFor();
await page.locator('[data-action=close]').first().click();await page.locator('.sidebar [data-view=photos]').click();await page.locator('[data-thumb]:visible').waitFor();await page.locator('[data-action=photo]').click();await page.locator('.viewer-media img').waitFor();
await page.locator('[data-action=download-photo]').click();const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=confirm-download]').click();await downloadPromise;
await page.locator('[data-action=upload]').first().click();await page.locator('#upload-files').setInputFiles({name:'prova.jpg',mimeType:'image/jpeg',buffer:readFileSync('assets/football.jpg')});assert.equal(await page.locator('#upload-form [type=submit]').isDisabled(),true,'upload requires privacy classification');await page.locator('#photo-no-players').check();failUpload=true;await page.locator('#upload-form [type=submit]').click();await page.locator('[data-action=retry-uploads]').waitFor();await page.locator('[data-action=retry-uploads]').click();await page.locator('.queue-item.done').waitFor();
assert.equal(uploads.length,2);assert.equal(uploads[0].foto_id,uploads[1].foto_id);assert.equal(uploads[0].request_id,uploads[1].request_id);assert.equal(uploads[0].sense_jugadors,true);assert.ok(Buffer.from(uploads[0].photo_base64,'base64').length<=1572864);
await page.locator('[data-action=close]').first().click();await context.setOffline(true);await page.locator('.offline-banner').waitFor();assert.equal(await page.locator('[data-action=upload]').first().isDisabled(),true);await context.setOffline(false);await page.locator('.offline-banner').waitFor({state:'hidden'});
await context.setOffline(true);await page.locator('[data-action=account]').first().click();await page.locator('[data-action=logout]').click();await page.locator('#login-form').waitFor();await secondPage.locator('#login-form').waitFor();assert.equal(await page.evaluate(()=>Object.keys(localStorage).length),0,'offline logout clears shared storage');assert.equal(await secondPage.evaluate(()=>document.querySelectorAll('img[src^="blob:"]').length),0,'offline logout clears private images in other tabs');await context.setOffline(false);
role='familia';const loginStart=apiCalls.length;let releaseRedeem,markRedeemStarted;const redeemStarted=new Promise(resolve=>markRedeemStarted=resolve);delayedRedeem={wait:new Promise(resolve=>releaseRedeem=resolve),started:markRedeemStarted};const staleRedeemResponse=secondPage.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='redeemInvite');await secondPage.locator('#login-phone').fill('999000123');await secondPage.locator('#login-code').fill('1234');await secondPage.locator('#login-form [type=submit]').click();await redeemStarted;
await page.locator('#login-phone').fill('999000123');await page.locator('#login-code').fill('1234');await page.locator('#login-form [type=submit]').click();await page.locator('.hero').waitFor();const currentLoginSession=await page.evaluate(key=>localStorage.getItem(key),sessionKey);releaseRedeem();await staleRedeemResponse;await secondPage.waitForTimeout(50);assert.equal(await page.evaluate(key=>localStorage.getItem(key),sessionKey),currentLoginSession,'a stale login response cannot replace the current session');assert.equal(await page.locator('.hero').count(),1);assert.equal(await secondPage.locator('#login-form').count(),1,'the stale login stays signed out');assert.deepEqual(apiCalls.slice(loginStart),['redeemInvite','redeemInvite'],'accepted users still enter without an extra bootstrap');
let releaseOldLogin,markOldLoginStarted;const oldLoginStarted=new Promise(resolve=>markOldLoginStarted=resolve);delayedRedeem={wait:new Promise(resolve=>releaseOldLogin=resolve),started:markOldLoginStarted,error:'Error antic d’entrada'};const oldLoginResponse=secondPage.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='redeemInvite');await secondPage.locator('#login-phone').fill('999000123');await secondPage.locator('#login-code').fill('1234');await secondPage.locator('#login-form [type=submit]').click();await oldLoginStarted;loginToken='overlap-login-token';await secondPage.locator('#login-phone').fill('999000123');await secondPage.locator('#login-code').fill('1234');const newLoginResponse=secondPage.waitForResponse(response=>response.url().startsWith('https://script.google.com/')&&JSON.parse(response.request().postData()||'{}').action==='redeemInvite');await secondPage.evaluate(()=>document.querySelector('#login-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await newLoginResponse;await secondPage.locator('.hero').waitFor();releaseOldLogin();await oldLoginResponse;assert.equal(await secondPage.locator('.error-panel').count(),0,'a late login error must not alter a later successful attempt');assert.equal(await secondPage.evaluate(key=>JSON.parse(localStorage.getItem(key)).token,sessionKey),'overlap-login-token');loginToken='synthetic-test-token';
await Promise.all([page.reload(),secondPage.reload()]);await Promise.all([page.locator('.hero').waitFor(),secondPage.locator('.hero').waitFor()]);await page.locator('[data-action=match]').first().click();assert.equal(await page.locator('[data-action=edit-match]').count(),0,'family cannot edit');await page.locator('[data-action=close]').first().click();revoked=true;await page.locator('[data-action=refresh]').click();await page.locator('#login-form').waitFor();await secondPage.locator('#login-form').waitFor();assert.equal(await page.evaluate(()=>Object.keys(localStorage).length),0,'revocation clears cached private snapshot in every tab');revoked=false;await secondPage.close();empty=true;combineBootstrap=false;const legacyStart=apiCalls.length;await page.locator('#login-phone').fill('999000123');await page.locator('#login-code').fill('1234');await page.locator('#login-form [type=submit]').click();await page.locator('.hero').waitFor();assert.deepEqual(apiCalls.slice(legacyStart),['redeemInvite','bootstrap'],'backends without combined bootstrap remain compatible');combineBootstrap=true;await page.screenshot({path:'test-output/home-empty-desktop.png',fullPage:true});await page.locator('.sidebar [data-view=calendar]').click();await page.getByText('La temporada ens espera').waitFor();
assert.deepEqual(errors,[]);
console.log('PASS: consent, responsive layouts, results, private gallery, download, upload retries, offline, logout, empty season.');


await page.locator('.sidebar [data-view=team]').click();await page.locator('.album-example').waitFor();assert.equal(await page.locator('[data-action=add-player]').count(),0,'old backend does not expose an unsupported editor');await page.evaluate(()=>document.getElementById('toast').hidden=true);await page.screenshot({path:'test-output/cards-empty-preview.png',fullPage:true});await page.locator('.sidebar [data-view=calendar]').click();
fixtureScenario=true;await page.locator('[data-action=refresh]').click();await page.locator('.match-row').nth(6).waitFor();
assert.equal(await page.locator('.match-row').count(),7,'exactly seven CF Vilajuïga fixtures');
await page.locator('[data-action=match][data-id="2026_27_f1_j01"]').click();await page.locator('.detail-top').waitFor();assert.ok((await page.locator('.detail-top').textContent()).includes('dissabte, 10 d’octubre'));assert.equal(await page.locator('.detail-info strong').first().innerText(),'10:00');assert.ok((await page.locator('.detail-info').innerText()).includes('Palau-saverdera'));await page.locator('[data-action=close]').click();
await page.locator('.sidebar [data-view=league]').click();await page.locator('.club-card').nth(7).waitFor();assert.equal(await page.locator('.club-card').count(),8);assert.equal(await page.locator('.our-club').count(),1);
assert.ok((await page.locator('[data-club=llers] .club-fixture').innerText()).includes('A casa'),'home match distinct from rival home ground');
assert.ok((await page.locator('[data-club=finca] .club-fixture').innerText()).includes('diumenge, 1 de novembre'));
const navataMap=await page.locator('[data-club=navata] a').getAttribute('href');assert.equal(navataMap,'https://maps.app.goo.gl/2aj47hjDicsMrnmKA');
await page.screenshot({path:'test-output/league-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.mobile-nav .nav-btn').count(),5);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile league overflow');await page.screenshot({path:'test-output/league-mobile.png',fullPage:true});
await page.locator('[data-club=finca] [data-action=club]').click();await page.locator('.club-sources').waitFor();assert.ok((await page.locator('.venue-note').innerText()).includes('accés'));await page.screenshot({path:'test-output/club-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'club detail overflow');
await page.locator('#modal .club-fixture').filter({hasText:'J4'}).click();await page.locator('.detail-top').waitFor();assert.equal(await page.locator('.detail-info strong').first().innerText(),'12:00');assert.ok((await page.locator('.detail-top').textContent()).includes('diumenge, 1 de novembre'));await page.locator('[data-action=close]').click();
await page.setViewportSize({width:360,height:780});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'360px league overflow');
await context.setOffline(true);await page.locator('.offline-banner').waitFor();assert.equal(await page.locator('.club-card').count(),8,'league remains available offline');await context.setOffline(false);await page.locator('.offline-banner').waitFor({state:'hidden'});
assert.deepEqual(errors,[]);console.log('PASS: seven PDF fixtures, home/away ground distinction, league cards, sources, maps, mobile and offline.');


await page.setViewportSize({width:1440,height:1000});role='admin';cardScenario=true;await page.locator('[data-action=refresh]').click();await page.locator('.sidebar [data-view=team]').click();await page.locator('[data-portrait]:visible').waitFor();assert.equal(await page.locator('.album-grid .football-card').count(),3);
await page.evaluate(()=>document.getElementById('toast').hidden=true);await page.screenshot({path:'test-output/cards-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'card album mobile overflow');await page.screenshot({path:'test-output/cards-mobile.png',fullPage:true});
await page.locator('[data-action=player]').first().click();await page.locator('#modal [data-portrait]:visible').waitFor();await page.screenshot({path:'test-output/card-detail-mobile.png',fullPage:true});await page.locator('[data-action=close]').click();

const portraitSession=await page.evaluate(key=>localStorage.getItem(key),sessionKey),accountSwitchPage=await context.newPage();accountSwitchPage.on('pageerror',e=>errors.push(e.message));await accountSwitchPage.goto('http://127.0.0.1:8080/');await accountSwitchPage.locator('.hero').waitFor();
await gateNextImagePreparation(page);await page.locator('[data-action=edit-player]').first().click();await page.locator('#player-name').fill('Retrat iniciat pel compte A');await page.locator('#player-portrait').setInputFiles({name:'retrat-sessio-a.jpg',mimeType:'image/jpeg',buffer:Buffer.from(portraitB64,'base64')});await page.locator('#player-form [type=submit]').click();await page.waitForFunction(()=>window.__imagePreparationStarted);
await accountSwitchPage.evaluate(key=>{const session=JSON.parse(localStorage.getItem(key));localStorage.setItem(key,JSON.stringify({...session,token:'portrait-account-b-seed',cacheKey:'portrait-account-b-seed-cache'}));},sessionKey);await page.locator('#login-form').waitFor();loginToken='portrait-account-b-token';await page.locator('#login-phone').fill('999000123');await page.locator('#login-code').fill('1234');await page.locator('#login-form [type=submit]').click();await page.locator('.hero').waitFor();await finishImagePreparation(page);
assert.equal(await page.evaluate(()=>window.__imageWrites.some(payload=>payload.action==='savePlayer'&&payload.token==='portrait-account-b-token')),false,'a portrait prepared by account A must never use account B credentials');assert.equal(await page.locator('.hero').count(),1,'an obsolete portrait operation must not alter the new account UI');assert.equal(await page.evaluate(()=>document.querySelectorAll('img[src^="blob:"]').length),0,'the old portrait preview must not survive the account change');
loginToken='synthetic-test-token';await accountSwitchPage.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:sessionKey,raw:portraitSession});await page.reload();await page.locator('.hero').waitFor();await accountSwitchPage.close();await page.locator('[data-action=navigate][data-view=team]:visible').click();await page.locator('[data-portrait]:visible').waitFor();

await page.locator('[data-action=edit-player]').first().click();await page.locator('#player-name').fill('Cromo de prova');await page.locator('#player-position').selectOption('Defensa');await page.locator('#player-portrait').setInputFiles({name:'retrat.jpg',mimeType:'image/jpeg',buffer:Buffer.from(portraitB64,'base64')});await page.locator('#player-live-preview .player-portrait').waitFor();failCardSave=true;await page.locator('#player-form [type=submit]').click();await page.locator('#player-error:visible').waitFor();await page.locator('#player-form [type=submit]').click();await page.locator('.album-grid').waitFor();assert.equal(cardSaves.length,2);assert.equal(cardSaves[0].request_id,cardSaves[1].request_id);assert.equal(cardSaves[0].foto_id,cardSaves[1].foto_id);assert.ok(Buffer.from(cardSaves[1].photo_base64,'base64').length<=409600);assert.equal(cardSaves[1].posicio,'Defensa');
await page.locator('[data-action=add-player]').first().click();await page.locator('#player-name').fill('Nou cromo');await page.locator('#player-jersey').fill('9');await page.locator('#player-position').selectOption('Davanter');await page.locator('#player-form [type=submit]').click();await page.locator('.album-grid .football-card').nth(3).waitFor();assert.equal(await page.locator('.album-grid .football-card').count(),4);
await page.setViewportSize({width:360,height:780});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'360px card overflow');
await context.setOffline(true);await page.locator('.offline-banner').waitFor();assert.equal(await page.locator('[data-action=edit-player]').first().isDisabled(),true);assert.equal(await page.locator('[data-portrait]:visible').count(),0,'private portraits removed on disconnect');await context.setOffline(false);await page.locator('.offline-banner').waitFor({state:'hidden'});
role='familia';await refreshed();await page.locator('.album-grid').waitFor();assert.equal(await page.locator('[data-action=edit-player]').count(),0);assert.equal(await page.locator('[data-action=add-player]').count(),0);assert.deepEqual(errors,[]);console.log('PASS: player cards, portrait privacy, editor previews, idempotent retries, add player, mobile and family permissions.');

async function refreshed(){
 const response=page.waitForResponse(r=>r.url().startsWith('https://script.google.com/')&&JSON.parse(r.request().postData()||'{}').action==='bootstrap');
 await page.locator('[data-action=refresh]').click();await response;await page.locator('[data-action=refresh]:enabled').waitFor();
}
await page.locator('[data-portrait]:visible').waitFor();
const portraitCount=()=>apiCalls.filter(a=>a==='getPlayerPortraits').length;
const savedPortrait=await page.locator('[data-player-card=card1] [data-portrait]').getAttribute('src'),savedCount=portraitCount();
await refreshed();assert.equal(portraitCount(),savedCount,'unchanged authorized portraits are not downloaded again');assert.equal(await page.locator('[data-player-card=card1] [data-portrait]').getAttribute('src'),savedPortrait);
players[0].retrat_version='changed-portrait';await refreshed();await page.locator('[data-player-card=card1] [data-portrait]:visible').waitFor();assert.equal(portraitCount(),savedCount+1,'a changed portrait is fetched once');
omitPortrait=true;await refreshed();assert.equal(await page.locator('[data-player-card=card1]').count(),0,'a newly restricted player disappears');
omitPortrait=false;await refreshed();await page.locator('[data-player-card=card1] [data-portrait]:visible').waitFor();
failBootstrap=true;await refreshed();await page.locator('.offline-banner').waitFor();assert.equal(await page.locator('[data-portrait]:visible').count(),0,'failed revalidation removes portraits');failBootstrap=false;await refreshed();await page.locator('[data-player-card=card1] [data-portrait]:visible').waitFor();
assert.equal(await page.evaluate(()=>Object.values(localStorage).some(v=>v.includes('base64')||v.includes('blob:'))),false,'private images are never persisted');
console.log('PASS: invite login/consent, family administration, portrait reuse, updated/restricted portraits and failed revalidation.');

// Both batches must start while responses are deliberately held. Navigation invalidates both.
let releasePortraits;portraitGate=new Promise(resolve=>releasePortraits=resolve);
for(let i=0;i<7;i++)players.push({jugador_id:'parallel'+i,nom:'Prova paral·lela '+i,dorsal:i+20,posicio:'Defensa',te_retrat:true,retrat_version:'parallel-portrait'+i,actualitzat_at:''});
const parallelStart=portraitCount();await refreshed();
for(let i=0;i<100&&portraitCount()<parallelStart+2;i++)await new Promise(resolve=>setTimeout(resolve,20));
assert.equal(portraitCount(),parallelStart+2,'two portrait batches start before either response is released');
await page.locator('.mobile-nav [data-view=calendar]').click();releasePortraits();portraitGate=null;
await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,100)));assert.equal(await page.locator('[data-portrait]').count(),0,'late portrait responses do not reattach to another view');
await page.locator('.mobile-nav [data-view=team]').click();await page.locator('[data-player-card=parallel6] [data-portrait]:visible').waitFor();assert.equal(portraitCount(),parallelStart+4,'returning to the album fetches freshly authorized portraits');
console.log('PASS: bounded parallel portrait loading and cancelled navigation cannot restore private images.');

async function displayedVersion(tab){await tab.locator('[data-action=about]').click();const text=await tab.locator('#modal').innerText(),match=text.match(/Versió (\d+\.\d+\.\d+)/);await tab.locator('#modal [data-action=close]').click();return match?.[1];}
legacyPwa=true;const swContext=await browser.newContext(),swPage=await swContext.newPage();await swPage.goto('http://127.0.0.1:8080/');await swPage.evaluate(()=>navigator.serviceWorker.ready);await swPage.reload();await swPage.locator('#login-phone').waitFor();const openTab=await swContext.newPage();await openTab.goto('http://127.0.0.1:8080/');await openTab.locator('#login-phone').waitFor();assert.equal(await displayedVersion(swPage),'4.0.0');assert.equal(await displayedVersion(openTab),'4.0.0');assert.ok((await swPage.evaluate(()=>caches.keys())).some(key=>key.endsWith('v4.0.0')),'the upgrade test must start with the 4.0.0 cache');
const firstControllerChange=swPage.evaluate(()=>new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true}))),secondControllerChange=openTab.evaluate(()=>new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true})));legacyPwa=false;await swPage.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();await registration.update();});await Promise.all([firstControllerChange,secondControllerChange]);
await swPage.waitForFunction(async()=>{const keys=await caches.keys();return keys.some(key=>key.endsWith('v4.0.1'));});const upgradedCache=await swPage.evaluate(async()=>{const key=(await caches.keys()).find(candidate=>candidate.endsWith('v4.0.1')),response=await(await caches.open(key)).match(new URL('./config.mjs',location.href));return {key,config:await response.text()};});assert.match(upgradedCache.config,/APP_VERSION='4\.0\.1'/,'the new cache contains the 4.0.1 resources');assert.equal(await displayedVersion(swPage),'4.0.0','activation does not replace JavaScript already running in the first tab');assert.equal(await displayedVersion(openTab),'4.0.0','activation does not replace JavaScript already running in another open tab');
await Promise.all([swPage.reload(),openTab.reload()]);await Promise.all([swPage.locator('#login-phone').waitFor(),openTab.locator('#login-phone').waitFor()]);assert.equal(await displayedVersion(swPage),'4.0.1');assert.equal(await displayedVersion(openTab),'4.0.1');assert.match(await swPage.evaluate(()=>fetch('./config.mjs').then(response=>response.text())),/APP_VERSION='4\.0\.1'/);await swContext.setOffline(true);await Promise.all([swPage.reload(),openTab.reload()]);await Promise.all([swPage.locator('#login-phone').waitFor(),openTab.locator('#login-phone').waitFor()]);const cacheUrls=await swPage.evaluate(async()=>{const cs=await caches.keys();return (await Promise.all(cs.map(async c=>(await(await caches.open(c)).keys()).map(r=>r.url)))).flat();});assert.ok(cacheUrls.length>=17);assert.ok(cacheUrls.some(u=>u.endsWith('/league.mjs')));assert.ok(cacheUrls.some(u=>u.endsWith('/media-batches.mjs')));assert.ok(cacheUrls.every(u=>u.startsWith('http://127.0.0.1:8080/')));console.log('PASS: v4.0.0 upgrades to v4.0.1; open tabs retain old runtime until reload; new shell works offline.');server.close();process.exit(0);
