const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'../Code.gs'),'utf8');
const PHONE={admin:'+34600111222',editor:'+34600222333',familia:'+34600333444'};
const clone=x=>JSON.parse(JSON.stringify(x));
const iterator=items=>{let i=0;return {hasNext:()=>i<items.length,next:()=>items[i++]};};
const bytes=b=>[...Buffer.from(b)].map(x=>x>127?x-256:x);
function setup(code=source){
  const properties=new Map(),cache=new Map(),sheets=new Map(),files=new Map(),folders=new Map();
  const metrics={spreadsheetOpens:0,tableReads:{},headerReads:{},folderLookups:0};
  const resetMetrics=()=>{metrics.spreadsheetOpens=0;metrics.tableReads={};metrics.headerReads={};metrics.folderLookups=0;};
  const failures={deleteIds:new Set(),createAt:0,created:0,writeName:null};
  let locked=false;
  function blob(b,mime='image/jpeg',name=''){const data=typeof b==='string'?Buffer.from(b):Buffer.from(b.map(x=>x&255));return {getBytes:()=>bytes(data),getDataAsString:()=>data.toString(),data,mime,name};}
  function range(sheet,row,col,nr,nc){return {
    getValues:()=>{const reads=row===1?metrics.headerReads:metrics.tableReads;reads[sheet.name]=(reads[sheet.name]||0)+1;return Array.from({length:nr},(_,i)=>Array.from({length:nc},(_,j)=>sheet.data[row-1+i]?.[col-1+j]??''));},
    setValues:values=>{if(failures.writeName===sheet.name)throw new Error('Injected sheet write failure');values.forEach((r,i)=>{sheet.data[row-1+i]??=[];r.forEach((v,j)=>sheet.data[row-1+i][col-1+j]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v);});return range(sheet,row,col,nr,nc);},
    setBackground(){return this;},setFontColor(){return this;},setFontWeight(){return this;}
  };}
  function sheet(name){const s={name,data:[],getLastRow:()=>s.data.length,getRange:(...args)=>range(s,...args),setFrozenRows(){},setName(n){sheets.delete(s.name);s.name=n;sheets.set(n,s);return s;}};sheets.set(name,s);return s;}
  const ss={getId:()=> 'sheet-id',getUrl:()=> 'https://docs.google.com/spreadsheets/d/sheet-id/edit',getSheetByName:n=>sheets.get(n),insertSheet:sheet,getSheets:()=>[...sheets.values()],setSpreadsheetTimeZone(){}};
  function file(id,name,folder,b){const f={id,name,folder,b,shared:false,editors:[],viewers:[],trashed:false,getId:()=>id,getName:()=>f.name,getMimeType:()=>f.mime||'image/jpeg',getSharingAccess:()=>f.shared?'ANYONE':'PRIVATE',getEditors:()=>f.editors,getViewers:()=>f.viewers,isTrashed:()=>f.trashed,getParents:()=>iterator(folder?[folder]:[]),getSize:()=>f.b.length,getBlob:()=>blob(f.b)};files.set(id,f);return f;}
  function folder(name,parent){const id=crypto.randomUUID();const f={name,id,parent,shared:false,getId:()=>id,getUrl:()=> 'https://drive.google.com/drive/folders/'+id,getSharingAccess:()=>f.shared?'ANYONE':'PRIVATE',getEditors:()=>[],getViewers:()=>[],getFoldersByName:n=>{metrics.folderLookups++;return iterator([...folders.values()].filter(x=>x.parent===f&&x.name===n));},createFolder:n=>folder(n,f),getFilesByName:n=>iterator([...files.values()].filter(x=>x.folder===f&&x.name===n)),getFiles:()=>iterator([...files.values()].filter(x=>x.folder===f)),createFile:b=>{failures.created++;if(failures.createAt===failures.created)throw new Error('Injected Drive create failure');return file(crypto.randomUUID(),b.name,f,b.data);}};folders.set(id,f);return f;}
  const ctx=vm.createContext({console:{log(){}},Date,Set,JSON,Math,Object,String,Number,Array,Error,
    PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v),deleteProperty:k=>properties.delete(k),getProperties:()=>Object.fromEntries(properties)})},
    CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})},
    LockService:{getScriptLock:()=>({tryLock:()=>{assert.equal(locked,false);locked=true;return true;},releaseLock:()=>{locked=false;}})},
    SpreadsheetApp:{openById:()=>{metrics.spreadsheetOpens++;return ss;},create:()=>{sheet('Sheet1');const f=file('sheet-id','Spreadsheet',null,Buffer.alloc(0));f.mime='application/vnd.google-apps.spreadsheet';return ss;},flush(){}},
    DriveApp:{Access:{PRIVATE:'PRIVATE'},createFolder:n=>folder(n,null),getFolderById:id=>{if(!folders.has(id))throw Error('Missing folder');return folders.get(id);},getFileById:id=>{if(!files.has(id))throw Error('Missing file');return files.get(id);}},
    Drive:{Files:{remove:id=>{if(failures.deleteIds.has(id))throw Error('Injected Drive delete failure');assert(files.has(id));files.delete(id);}}},
    ContentService:{MimeType:{JSON:'application/json'},createTextOutput:s=>({text:s,setMimeType(){return this;}})},
    Utilities:{Charset:{UTF_8:'UTF-8'},getUuid:()=>crypto.randomUUID(),newBlob:blob,
      base64Encode:arr=>Buffer.from(arr.map(x=>x&255)).toString('base64'),base64Decode:s=>bytes(Buffer.from(s,'base64')),
      base64EncodeWebSafe:v=>(typeof v==='string'?Buffer.from(v):Buffer.from(v.map(x=>x&255))).toString('base64url'),base64DecodeWebSafe:s=>bytes(Buffer.from(s,'base64url')),
      computeHmacSha256Signature:(s,k)=>bytes(crypto.createHmac('sha256',k).update(s).digest()),
      formatDate:(d,tz,fmt)=>{assert.equal(fmt,'yyyy-MM-dd');return new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);},
      parseCsv:text=>text.trim().split('\n').map(r=>r.split(','))
    }
  });vm.runInContext(code,ctx);ctx.installBackend();
  for(const [role,n] of Object.entries(PHONE))ctx.addUser(n,role,role);
  const config=(k,v)=>{const r=ctx.unique_(ctx.rows_('02_CONFIG'),'clau',k);r.valor=v;ctx.put_('02_CONFIG',r,r._row);};
  const call=p=>clone(JSON.parse(ctx.doPost({postData:{contents:JSON.stringify(p)}}).text));
  const login=(role='admin',codi)=>call({action:'login',telefon:PHONE[role],...(codi?{codi}:{})});
  const req=(action,token,extra={})=>call({action,token,request_id:crypto.randomUUID(),...extra});
  const accept=token=>req('acceptPrivacy',token,{accepted:true,version:'1'});
  const session=(role='admin')=>{const r=login(role);assert(r.ok);accept(r.data.token);return r.data.token;};
  const match={partit_id:'P001',jornada:1,data:'2026-10-10',hora:'10:30',local:'CF VILAJUÏGA',visitant:'UE FIGUERES',camp_nom:'Camp de prova',camp_adreca:'',camp_lat:'',camp_lng:'',estat:'pendent',gols_local:'',gols_visitant:'',cronica:'',visible:true,actualitzat_at:'',actualitzat_per:''};ctx.put_('01_PARTITS',match);
  ctx.put_('05_JUGADORS',{jugador_id:'J01',nom:'Prova',dorsal:4,no_mostrar:false,actiu:true});
  // Small marker fixture tests the parser, not a complete JPEG decoder. Full JPEG fixture separately below.
  const jpeg=Buffer.from([255,216,255,192,0,11,8,0,1,0,1,1,1,17,0,255,218,0,8,1,1,0,0,63,0,1,255,217]).toString('base64');
  const upload=(token,extra={})=>req('uploadPhoto',token,{foto_id:crypto.randomUUID(),partit_id:'P001',photo_base64:jpeg,thumb_base64:jpeg,jugadors_ids:['J01'],peu:'',...extra});
  const setUser=(role,values)=>{const u=ctx.unique_(ctx.users_(true),'telefon',PHONE[role]);Object.assign(u,values);ctx.put_('03_USUARIS',u,u._row);ctx.invalidateUsers_();};
  return {ctx,call,req,login,accept,session,upload,config,properties,cache,sheets,files,folders,failures,setUser,jpeg,metrics,resetMetrics};
}
const tests=[];function test(name,fn){tests.push([name,fn]);}function error(r,code){assert.equal(r.ok,false);assert.equal(r.error.code,code);}
test('installation is repeatable, six tables, no fake users or fixtures added by installer',()=>{const t=setup();t.ctx.installBackend();assert.equal(t.sheets.size,6);assert.equal(t.ctx.rows_('03_USUARIS').length,3);assert.equal(t.ctx.rows_('01_PARTITS').length,1);});
test('unknown action, malformed JSON, public GET expose no secrets',()=>{const t=setup();error(t.call({action:'addUser'}),'UNKNOWN_ACTION');const r=JSON.parse(t.ctx.doPost({postData:{contents:'{bad'}}).text);error(r,'BAD_JSON');const health=JSON.parse(t.ctx.doGet({parameter:{action:'health'}}).text);assert.equal(health.data.configured,true);assert(!JSON.stringify(health).includes('SESSION_SECRET'));});
test('phone normalisation, unknown and inactive user rejection',()=>{const t=setup();assert.equal(t.ctx.phone_('600 111 222'),PHONE.admin);assert.equal(t.ctx.phone_('0034 600111222'),PHONE.admin);error(t.call({action:'login',telefon:'699888777'}),'INVALID_LOGIN');t.setUser('admin',{actiu:false});error(t.login(),'INVALID_LOGIN');});
test('privacy gate is enforced at backend, old version rejected',()=>{const t=setup(),r=t.login(),token=r.data.token;error(t.req('bootstrap',token),'PRIVACY_REQUIRED');error(t.req('acceptPrivacy',token,{accepted:false,version:'1'}),'VALIDATION');t.accept(token);assert(t.req('bootstrap',token).ok);t.config('privacy_version','2');error(t.req('bootstrap',token),'PRIVACY_REQUIRED');});
test('token tampering, expiry and future issuance are rejected',()=>{const t=setup(),token=t.session();error(t.req('bootstrap',token+'x'),'UNAUTHORIZED');const [b]=token.split('.'),s=JSON.parse(Buffer.from(b,'base64url'));s.expiresAt=Date.now()-1;let body=Buffer.from(JSON.stringify(s)).toString('base64url');error(t.req('bootstrap',body+'.'+t.ctx.hmac_(body)),'UNAUTHORIZED');s.expiresAt=Date.now()+10000000;s.issuedAt=Date.now()+120000;body=Buffer.from(JSON.stringify(s)).toString('base64url');error(t.req('bootstrap',body+'.'+t.ctx.hmac_(body)),'UNAUTHORIZED');});
test('deactivation is immediate for media and writes; logout revokes token',()=>{const t=setup(),token=t.session();t.setUser('admin',{actiu:false});error(t.req('getPhoto',token,{foto_id:crypto.randomUUID()}),'UNAUTHORIZED');t.setUser('admin',{actiu:true});assert(t.req('logout',token).ok);error(t.req('bootstrap',token),'UNAUTHORIZED');});
test('current role and phone-only to code switch invalidate authority/sessions',()=>{const t=setup(),token=t.session();t.setUser('admin',{rol:'familia'});error(t.req('updateResult',token,{partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:2,gols_visitant:1}),'FORBIDDEN');for(const n of Object.values(PHONE))t.ctx.setUserCode(n,'123456');t.ctx.setLoginMode('telefon+codi');error(t.req('bootstrap',token),'UNAUTHORIZED');error(t.login('admin','654321'),'INVALID_LOGIN');assert(t.login('admin','123456').ok);assert(!JSON.stringify(t.ctx.rows_('03_USUARIS')).includes('123456'));});
test('code activation refuses missing active user codes; unknown config fails closed',()=>{const t=setup();assert.throws(()=>t.ctx.setLoginMode('telefon+codi'));t.config('login_mode','anything');error(t.login(),'SCHEMA_ERROR');});
test('five login attempts per phone until advisory rate limit',()=>{const t=setup();for(let i=0;i<5;i++)assert(t.login().ok);error(t.login(),'RATE_LIMIT');});
test('one LOGIN per local day, acceptance retry does not duplicate audit',()=>{const t=setup(),r=t.login(),token=r.data.token,id=crypto.randomUUID();t.login();assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='LOGIN').length,1);assert(t.req('acceptPrivacy',token,{request_id:id,accepted:true,version:'1'}).ok);assert(t.req('acceptPrivacy',token,{request_id:id,accepted:true,version:'1'}).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='ACCEPT_PRIVACY').length,1);});
test('results: permission, type validation, optimistic conflict and retry',()=>{const t=setup(),token=t.session('editor'),payload={partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:3,gols_visitant:2,request_id:crypto.randomUUID()};error(t.req('updateResult',token,{...payload,gols_local:'3'}),'VALIDATION');const r=t.req('updateResult',token,payload);assert(r.ok);assert(t.req('updateResult',token,payload).data.replayed);error(t.req('updateResult',token,{...payload,request_id:crypto.randomUUID()}),'CONFLICT');assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_RESULT').length,1);});
test('chronicle text starting with formula is stored literally; bootstrap has no private phones',()=>{const t=setup(),token=t.session('editor');assert(t.req('updateChronicle',token,{partit_id:'P001',expected_updated_at:'',cronica:'=IMPORTXML("secret")'}).ok);assert.equal(t.ctx.rows_('01_PARTITS')[0].cronica,'=IMPORTXML("secret")');const data=t.req('bootstrap',token).data;assert(!JSON.stringify(data).includes(PHONE.editor));assert(!JSON.stringify(data).includes('hmac-v1'));});
test('stats home/away, draws and non-team fixtures',()=>{const t=setup();const c=t.ctx.config_(),base=t.ctx.rows_('01_PARTITS')[0];const s=t.ctx.statistics_([{...base,estat:'jugat',gols_local:3,gols_visitant:2},{...base,local:'Other',visitant:c.equip_nom,estat:'jugat',gols_local:0,gols_visitant:2},{...base,estat:'jugat',gols_local:1,gols_visitant:1},{...base,local:'X',visitant:'Y',estat:'jugat',gols_local:9,gols_visitant:0}],c);assert.deepEqual(clone(s),{PJ:3,V:2,E:1,D:0,GF:6,GC:3,DG:3});});
test('family upload idempotent with same photo_id, no Drive IDs or uploader phone exposed',()=>{const t=setup(),token=t.session('familia'),id=crypto.randomUUID();const r=t.upload(token,{foto_id:id});assert(r.ok);assert(!JSON.stringify(r).includes('drive_file_id'));assert(!JSON.stringify(r).includes(PHONE.familia));const again=t.upload(token,{foto_id:id});assert(again.data.replayed);assert.equal(t.ctx.rows_('04_FOTOS').length,1);assert.equal([...t.files.values()].filter(f=>f.mime!=='application/vnd.google-apps.spreadsheet').length,2);});
test('JPEG validation rejects oversized, invalid dimensions, malformed base64 and GPS metadata',()=>{const t=setup(),token=t.session();error(t.upload(token,{photo_base64:'bad'}),'VALIDATION');let b=Buffer.from(t.jpeg,'base64');b[9]=7;b[10]=208;error(t.upload(token,{photo_base64:b.toString('base64')}),'VALIDATION');const exif=Buffer.concat([Buffer.from([255,216,255,225,0,4,1,2]),Buffer.from(t.jpeg,'base64').subarray(2)]);error(t.upload(token,{photo_base64:exif.toString('base64')}),'VALIDATION');error(t.call({action:'uploadPhoto',padding:'x'.repeat(2400001)}),'PAYLOAD_TOO_LARGE');});
test('upload cleans first file if thumbnail creation fails',()=>{const t=setup(),token=t.session();t.failures.createAt=2;error(t.upload(token),'INTERNAL_ERROR');assert.equal(t.ctx.rows_('04_FOTOS').length,0);assert.equal(t.files.size,1);});
test('upload whose audit failed can recover without duplicating photo files',()=>{const t=setup(),token=t.session(),id=crypto.randomUUID(),request_id=crypto.randomUUID();t.failures.writeName='06_REGISTRE';error(t.upload(token,{foto_id:id,request_id}),'INTERNAL_ERROR');assert.equal(t.ctx.rows_('04_FOTOS').length,1);t.failures.writeName=null;assert(t.upload(token,{foto_id:id,request_id}).ok);assert.equal(t.files.size,3);});
test('hidden photo, player restriction and blank privacy flag block normal retrieval',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),r=t.upload(admin),id=r.data.foto.foto_id;assert(t.req('getPhoto',family,{foto_id:id}).ok);const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);error(t.req('getPhoto',family,{foto_id:id,include_hidden:true}),'NOT_FOUND');error(t.req('getPhoto',admin,{foto_id:id}),'NOT_FOUND');assert(t.req('getPhoto',admin,{foto_id:id,include_hidden:true}).ok);assert.equal(t.req('listPhotos',family,{partit_id:'P001'}).data.fotos.length,0);j.no_mostrar='';t.ctx.put_('05_JUGADORS',j,j._row);error(t.req('getPhoto',family,{foto_id:id}),'NOT_FOUND');});
test('SHOW_PHOTO does not bypass a blocked player, family cannot hide/delete',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),id=t.upload(admin).data.foto.foto_id;error(t.req('hidePhoto',family,{foto_id:id}),'FORBIDDEN');assert(t.req('hidePhoto',admin,{foto_id:id,motiu:'Privacitat'}).ok);error(t.req('getPhoto',family,{foto_id:id}),'NOT_FOUND');const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);assert(t.req('showPhoto',admin,{foto_id:id}).data.foto.bloquejada);error(t.req('getPhoto',family,{foto_id:id}),'NOT_FOUND');error(t.req('deletePhoto',family,{foto_id:id,confirm_permanent:true}),'FORBIDDEN');});
test('private file parent, name and sharing are checked, arbitrary Drive ID ignored',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id,f=t.ctx.rows_('04_FOTOS')[0],file=t.files.get(f.drive_file_id);file.shared=true;error(t.req('getPhoto',token,{foto_id:id}),'DRIVE_NOT_PRIVATE');file.shared=false;file.name='different.jpg';error(t.req('getPhoto',token,{foto_id:id}),'NOT_FOUND');error(t.req('getPhoto',token,{foto_id:crypto.randomUUID(),drive_file_id:f.drive_file_id}),'NOT_FOUND');});
test('download ack required, audit always records initiated downloads, retries deduplicated',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id;error(t.req('downloadPhoto',token,{foto_id:id}),'VALIDATION');const request_id=crypto.randomUUID();assert(t.req('downloadPhoto',token,{foto_id:id,private_use_ack:true,request_id}).ok);assert(t.req('downloadPhoto',token,{foto_id:id,private_use_ack:true,request_id}).ok);assert(t.req('downloadPhoto',token,{foto_id:id,private_use_ack:true}).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='DOWNLOAD_PHOTO').length,2);});
test('thumbnail batches capped at six and individually hide forbidden items',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),id=t.upload(admin).data.foto.foto_id;error(t.req('getThumbnails',family,{foto_ids:Array.from({length:7},()=>crypto.randomUUID())}),'VALIDATION');const r=t.req('getThumbnails',family,{foto_ids:[id,crypto.randomUUID()]});assert(r.ok);assert(r.data.items[0].ok);assert.equal(r.data.items[1].error.code,'NOT_FOUND');});
test('partial deletion tombstones photo, retries finish remaining files, confirmation required',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id,f=t.ctx.rows_('04_FOTOS')[0],request_id=crypto.randomUUID();error(t.req('deletePhoto',token,{foto_id:id}),'VALIDATION');t.failures.deleteIds.add(f.thumb_file_id);const r=t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true,request_id});assert(r.data.pending);error(t.req('getPhoto',token,{foto_id:id,include_hidden:true}),'NOT_FOUND');t.failures.deleteIds.clear();assert(t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true,request_id}).data.permanent);assert.equal(t.files.size,1);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='DELETE_PHOTO_COMPLETE').length,1);assert(t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true,request_id}).data.deleted);});
test('missing Drive file is reported pending rather than falsely claiming permanent deletion',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id,f=t.ctx.rows_('04_FOTOS')[0];t.files.delete(f.drive_file_id);const r=t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true});assert(r.data.pending);assert.equal(r.data.deleted,false);});
test('corrupt headers and duplicate IDs fail closed',()=>{const t=setup();t.sheets.get('03_USUARIS').data[0][0]='bad';error(t.login(),'SCHEMA_ERROR');});
test('calendar invalid row rejects entire import before any writes',()=>{const t=setup(),csv='partit_id,jornada,data,hora,local,visitant,camp_nom,camp_adreca,camp_lat,camp_lng\nP002,2,2026-10-17,12:00,CF VILAJUÏGA,Other,Camp,,,\nP003,3,2026-02-30,12:00,CF VILAJUÏGA,Other,Camp,,,';assert.throws(()=>t.ctx.importCalendar(csv));assert.equal(t.ctx.rows_('01_PARTITS').length,1);});
test('result journal recovers failed audit and blocks competing edits until retry',()=>{const t=setup(),token=t.session('editor'),payload={partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:4,gols_visitant:0,request_id:crypto.randomUUID()};t.failures.writeName='06_REGISTRE';error(t.req('updateResult',token,payload),'INTERNAL_ERROR');assert.equal(t.ctx.rows_('01_PARTITS')[0].gols_local,4);assert(t.properties.has('pendingMatch:P001'));t.failures.writeName=null;error(t.req('updateChronicle',token,{partit_id:'P001',expected_updated_at:t.ctx.rows_('01_PARTITS')[0].actualitzat_at,cronica:'New'}),'BUSY');assert(t.req('updateResult',token,payload).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_RESULT').length,1);assert(!t.properties.has('pendingMatch:P001'));});
test('editor-only recovery completes already applied update audit after lost session',()=>{const t=setup(),token=t.session('editor');t.failures.writeName='06_REGISTRE';error(t.req('updateChronicle',token,{partit_id:'P001',expected_updated_at:'',cronica:'Updated',request_id:crypto.randomUUID()}),'INTERNAL_ERROR');t.failures.writeName=null;const r=t.ctx.recoverPendingMatchAudits();assert.equal(r[0].status,'audited');assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_CHRONICLE').length,1);assert(!t.properties.has('pendingMatch:P001'));});
test('failed match write leaves journal, same request commits once after retry',()=>{const t=setup(),token=t.session('editor'),payload={partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:1,gols_visitant:1,request_id:crypto.randomUUID()};t.failures.writeName='01_PARTITS';error(t.req('updateResult',token,payload),'INTERNAL_ERROR');t.failures.writeName=null;assert(t.req('updateResult',token,payload).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_RESULT').length,1);});
test('real canvas-compatible JPEG passes size and dimension parser',()=>{const t=setup(),j=t.ctx.jpeg_('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBAUEBAYFBQUGBgYHCQ4JCQgICRINDQoOFRIWFhUSFBQXGiEcFxgfGRQUHScdHyIjJSUlFhwpLCgkKyEkJST/2wBDAQYGBgkICREJCREkGBQYJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCT/wAARCAADAAIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDy+iiivOPnj//Z',1572864,1600);assert.equal(j.width,2);assert.equal(j.height,3);});

function playerPayload(t,extra={}){return {jugador_id:'J01',nom:'Prova',dorsal:4,posicio:'Migcampista',expected_updated_at:'',...extra};}
test('player schema upgrade preserves original columns and data, refuses conflicting header',()=>{const t=setup(),s=t.sheets.get('05_JUGADORS');s.data[0]=s.data[0].slice(0,5);t.ctx.installBackend();assert.equal(s.data[0].length,11);assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Prova');s.data[0][5]='personal';assert.throws(()=>t.ctx.installBackend());});
test('only admin can save player cards; restricted flags are preserved',()=>{const t=setup(),family=t.session('familia'),admin=t.session();error(t.req('savePlayer',family,playerPayload(t)),'FORBIDDEN');const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);const r=t.req('savePlayer',admin,playerPayload(t,{nom:'Nou nom',no_mostrar:false}));assert(r.ok);assert.equal(r.data.jugador.no_mostrar,true);assert.equal(t.req('bootstrap',family).data.jugadors.length,0);});
test('player portrait save, permissions, private folder and bootstrap omit Drive IDs',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),r=t.req('savePlayer',admin,playerPayload(t,{photo_base64:t.jpeg,foto_id:crypto.randomUUID()}));assert(r.ok);assert(r.data.jugador.te_retrat);assert(!JSON.stringify(r).includes('foto_drive_file_id'));const b=t.req('bootstrap',family).data;assert(b.features.player_cards);assert.equal(b.jugadors[0].posicio,'Migcampista');assert(!JSON.stringify(b).includes('foto_drive_file_id'));const media=t.req('getPlayerPortraits',family,{jugador_ids:['J01']});assert(media.data.items[0].ok);assert.equal(media.data.items[0].base64,t.jpeg);const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);assert(!t.req('getPlayerPortraits',family,{jugador_ids:['J01'],include_hidden:true}).data.items[0].ok);assert(!t.req('getPlayerPortraits',admin,{jugador_ids:['J01']}).data.items[0].ok);assert(t.req('getPlayerPortraits',admin,{jugador_ids:['J01'],include_hidden:true}).data.items[0].ok);});
test('portrait ID, folder, file name and sharing are verified on every read',()=>{const t=setup(),admin=t.session();t.req('savePlayer',admin,playerPayload(t,{photo_base64:t.jpeg,foto_id:crypto.randomUUID()}));const j=t.ctx.rows_('05_JUGADORS')[0],file=t.files.get(j.foto_drive_file_id);file.shared=true;assert(!t.req('getPlayerPortraits',admin,{jugador_ids:['J01']}).data.items[0].ok);file.shared=false;file.name='wrong.jpg';assert(!t.req('getPlayerPortraits',admin,{jugador_ids:['J01'],drive_file_id:j.foto_drive_file_id}).data.items[0].ok);error(t.req('getPlayerPortraits',admin,{jugador_ids:Array.from({length:7},(_,i)=>'J'+i)}),'VALIDATION');});
test('player save retries recover failed audit without duplicating portrait, reject altered request',()=>{const t=setup(),admin=t.session(),request_id=crypto.randomUUID(),p=playerPayload(t,{request_id,photo_base64:t.jpeg,foto_id:crypto.randomUUID()});t.failures.writeName='06_REGISTRE';error(t.req('savePlayer',admin,p),'INTERNAL_ERROR');const files=t.files.size;t.failures.writeName=null;assert(t.req('savePlayer',admin,p).data.replayed);assert.equal(t.files.size,files);error(t.req('savePlayer',admin,{...p,nom:'Changed'}),'CONFLICT');assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='SAVE_PLAYER').length,1);error(t.req('savePlayer',admin,playerPayload(t)),'CONFLICT');});
test('failed player row write cleans newly created portrait; original player is intact',()=>{const t=setup(),admin=t.session(),files=t.files.size;t.failures.writeName='05_JUGADORS';error(t.req('savePlayer',admin,playerPayload(t,{photo_base64:t.jpeg,foto_id:crypto.randomUUID()})),'INTERNAL_ERROR');assert.equal(t.files.size,files);assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Prova');});
test('new player card gets active flag and escaped formula-safe name; invalid fields rejected',()=>{const t=setup(),admin=t.session();error(t.req('savePlayer',admin,playerPayload(t,{dorsal:100})),'VALIDATION');error(t.req('savePlayer',admin,playerPayload(t,{posicio:'Unknown'})),'VALIDATION');error(t.req('savePlayer',admin,playerPayload(t,{photo_base64:'bad',foto_id:crypto.randomUUID()})),'VALIDATION');const r=t.req('savePlayer',admin,playerPayload(t,{jugador_id:'J02',nom:'=PROVA',dorsal:''}));assert(r.ok);assert.equal(t.ctx.rows_('05_JUGADORS')[1].nom,'=PROVA');assert.equal(t.ctx.rows_('05_JUGADORS')[1].actiu,true);});
test('six thumbnails read each table once and reuse the validated parent folder',()=>{
  const t=setup(),token=t.session('familia'),ids=Array.from({length:6},()=>t.upload(token).data.foto.foto_id);
  t.resetMetrics();const result=t.req('getThumbnails',token,{foto_ids:ids});
  assert(result.ok);assert.equal(result.data.items.filter(x=>x.ok).length,6);
  assert.equal(t.metrics.spreadsheetOpens,1);
  assert(Object.values(t.metrics.tableReads).every(n=>n===1));
  assert(Object.values(t.metrics.headerReads).every(n=>n===1));assert.equal(t.metrics.folderLookups,1);
  // A later request must see manual restrictions, changed sharing and changed headers.
  const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);
  assert(t.req('getThumbnails',token,{foto_ids:ids}).data.items.every(x=>!x.ok));
  j.no_mostrar=false;t.ctx.put_('05_JUGADORS',j,j._row);
  const f=t.ctx.rows_('04_FOTOS')[0],folder=t.files.get(f.thumb_file_id).folder;folder.shared=true;
  assert(t.req('getThumbnails',token,{foto_ids:ids}).data.items.every(x=>!x.ok));folder.shared=false;
  t.sheets.get('04_FOTOS').data[0][0]='incorrect';
  assert(t.req('getThumbnails',token,{foto_ids:ids}).data.items.every(x=>!x.ok));
});
test('combined login and consent bootstrap never expose data before current acceptance',()=>{
  const t=setup(),r=t.call({action:'login',telefon:PHONE.admin,include_bootstrap:true});
  assert(r.ok);assert.equal(r.data.bootstrap,undefined);
  const token=r.data.token,request_id=crypto.randomUUID();
  error(t.req('acceptPrivacy',token,{accepted:true,version:'0',include_bootstrap:true}),'VALIDATION');
  const accepted=t.req('acceptPrivacy',token,{request_id,accepted:true,version:'1',include_bootstrap:true});
  assert(accepted.data.bootstrap.features.fresh_permissions);assert.equal(accepted.data.bootstrap.partits.length,1);
  const retry=t.req('acceptPrivacy',token,{request_id,accepted:true,version:'1',include_bootstrap:true});assert(retry.data.bootstrap.user.privacyAccepted);
  assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='ACCEPT_PRIVACY').length,1);
  const next=t.call({action:'login',telefon:PHONE.admin,include_bootstrap:true});assert(next.data.bootstrap.user.privacyAccepted);
  assert.equal(t.login().data.bootstrap,undefined,'old clients retain the original response');
  t.config('privacy_version','2');assert.equal(t.call({action:'login',telefon:PHONE.admin,include_bootstrap:true}).data.bootstrap,undefined);
});
test('bootstrap does not reuse a previous user cache after manual role or activation changes',()=>{
  const t=setup(),token=t.session();assert(t.req('bootstrap',token).data.features.fresh_permissions);
  // Simulate direct Sheet editing without calling invalidateUsers_.
  const s=t.sheets.get('03_USUARIS');s.data[1][2]='familia';
  assert.equal(t.req('bootstrap',token).data.user.rol,'familia');
  s.data[1][4]=false;error(t.req('bootstrap',token),'UNAUTHORIZED');
});
test('request snapshots isolate unsaved edits, reflect writes, and are discarded after failure',()=>{
  const t=setup();
  t.ctx.inRequest_(()=>{
    const j=t.ctx.rows_('05_JUGADORS')[0];j.nom='Unsaved';
    assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Prova');
    t.ctx.put_('05_JUGADORS',j,j._row);assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Unsaved');
  });
  assert.throws(()=>t.ctx.inRequest_(()=>{t.ctx.rows_('05_JUGADORS');throw Error('Injected');}));
  t.sheets.get('05_JUGADORS').data[1][1]='Manual change';
  assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Manual change');
});
module.exports={setup,PHONE};
if(require.main===module){
let passed=0;for(const [name,fn]of tests){try{fn();console.log('PASS '+name);passed++;}catch(e){console.error('FAIL '+name+'\n'+e.stack);process.exitCode=1;}}
console.log(`${passed}/${tests.length} passed`);

}
