const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'../Code.gs'),'utf8');
const PHONE={admin:'+34600111222',editor:'+34600222333',familia:'+34600333444'};
const clone=x=>JSON.parse(JSON.stringify(x));
const iterator=items=>{let i=0;return {hasNext:()=>i<items.length,next:()=>items[i++]};};
const bytes=b=>[...Buffer.from(b)].map(x=>x>127?x-256:x);
function setup(code=source){
  const properties=new Map(),cache=new Map(),sheets=new Map(),files=new Map(),folders=new Map();
  const metrics={spreadsheetOpens:0,tableReads:{},headerReads:{},folderLookups:0,fileReads:0,folderReads:0,advancedFileReads:0,metadataReads:0,aclReads:0,parentReads:0,blobReads:0};
  const resetMetrics=()=>{metrics.spreadsheetOpens=0;metrics.tableReads={};metrics.headerReads={};metrics.folderLookups=0;metrics.fileReads=0;metrics.folderReads=0;metrics.advancedFileReads=0;metrics.metadataReads=0;metrics.aclReads=0;metrics.parentReads=0;metrics.blobReads=0;};
  const failures={deleteIds:new Set(),createAt:0,created:0,writeName:null};
  let locked=false;
  function blob(b,mime='image/jpeg',name=''){const data=typeof b==='string'?Buffer.from(b):Buffer.from(b.map(x=>x&255));return {getBytes:()=>bytes(data),getDataAsString:()=>data.toString(),data,mime,name};}
  function range(sheet,row,col,nr,nc){return {
    getValues:()=>{const reads=row===1?metrics.headerReads:metrics.tableReads;reads[sheet.name]=(reads[sheet.name]||0)+1;return Array.from({length:nr},(_,i)=>Array.from({length:nc},(_,j)=>sheet.data[row-1+i]?.[col-1+j]??''));},
    setValues:values=>{if(failures.writeName===sheet.name)throw new Error('Injected sheet write failure');values.forEach((r,i)=>{sheet.data[row-1+i]??=[];r.forEach((v,j)=>sheet.data[row-1+i][col-1+j]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v);});return range(sheet,row,col,nr,nc);},
    setValue:value=>{sheet.data[row-1]??=[];sheet.data[row-1][col-1]=value;return range(sheet,row,col,nr,nc);},
    setBackground(){return this;},setFontColor(){return this;},setFontWeight(){return this;},setNumberFormat(){return this;}
  };}
  function sheet(name){const s={name,data:[],getLastRow:()=>s.data.length,getMaxRows:()=>1000,getRange:(...args)=>range(s,...args),deleteRow:r=>s.data.splice(r-1,1),setFrozenRows(){},setName(n){sheets.delete(s.name);s.name=n;sheets.set(n,s);return s;}};sheets.set(name,s);return s;}
  const ss={getId:()=> 'sheet-id',getUrl:()=> 'https://docs.google.com/spreadsheets/d/sheet-id/edit',getSheetByName:n=>sheets.get(n),insertSheet:sheet,getSheets:()=>[...sheets.values()],setSpreadsheetTimeZone(){}};
  function file(id,name,folder,b){const f={id,name,folder,b,shared:false,editors:[],viewers:[],trashed:false,getId:()=>id,getName:()=>{metrics.metadataReads++;return f.name;},getMimeType:()=>{metrics.metadataReads++;return f.mime||'image/jpeg';},getSharingAccess:()=>{metrics.aclReads++;return f.shared?'ANYONE':'PRIVATE';},getEditors:()=>{metrics.aclReads++;return f.editors;},getViewers:()=>{metrics.aclReads++;return f.viewers;},isTrashed:()=>{metrics.metadataReads++;return f.trashed;},getParents:()=>{metrics.parentReads++;return iterator(folder?[folder]:[]);},getSize:()=>{metrics.metadataReads++;return f.b.length;},getBlob:()=>{metrics.blobReads++;return blob(f.b);}};files.set(id,f);return f;}
  function folder(name,parent){const id=crypto.randomUUID();const f={name,id,parent,shared:false,getId:()=>id,getUrl:()=> 'https://drive.google.com/drive/folders/'+id,getSharingAccess:()=>{metrics.aclReads++;return f.shared?'ANYONE':'PRIVATE';},getEditors:()=>{metrics.aclReads++;return [];},getViewers:()=>{metrics.aclReads++;return [];},getFoldersByName:n=>{metrics.folderLookups++;return iterator([...folders.values()].filter(x=>x.parent===f&&x.name===n));},createFolder:n=>folder(n,f),getFilesByName:n=>iterator([...files.values()].filter(x=>x.folder===f&&x.name===n)),getFiles:()=>iterator([...files.values()].filter(x=>x.folder===f)),createFile:b=>{failures.created++;if(failures.createAt===failures.created)throw new Error('Injected Drive create failure');return file(crypto.randomUUID(),b.name,f,b.data);}};folders.set(id,f);return f;}
  const ctx=vm.createContext({console:{log(){},warn(){}},Date,Set,JSON,Math,Object,String,Number,Array,Error,
    PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v),deleteProperty:k=>properties.delete(k),getProperties:()=>Object.fromEntries(properties)})},
    CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})},
    LockService:{getScriptLock:()=>({tryLock:()=>{assert.equal(locked,false);locked=true;return true;},releaseLock:()=>{locked=false;}})},
    SpreadsheetApp:{openById:()=>{metrics.spreadsheetOpens++;return ss;},create:()=>{sheet('Sheet1');const f=file('sheet-id','Spreadsheet',null,Buffer.alloc(0));f.mime='application/vnd.google-apps.spreadsheet';return ss;},flush(){}},
    DriveApp:{Access:{PRIVATE:'PRIVATE'},createFolder:n=>folder(n,null),getFolderById:id=>{metrics.folderReads++;if(!folders.has(id))throw Error('Missing folder');return folders.get(id);},getFileById:id=>{metrics.fileReads++;if(!files.has(id))throw Error('Missing file');return files.get(id);}},
    Drive:{Files:{get:id=>{metrics.advancedFileReads++;const f=files.get(id);if(!f)throw Error('Missing file');return {id,title:f.name,mimeType:f.mime||'image/jpeg',fileSize:String(f.b.length),labels:{trashed:f.trashed},parents:f.folder?[{id:f.folder.id}]:[],permissions:[{role:'owner',type:'user'},...(f.shared?[{role:'reader',type:'anyone'}]:[]),...f.editors.map(()=>({role:'writer',type:'user'})),...f.viewers.map(()=>({role:'reader',type:'user'}))]};},remove:id=>{if(failures.deleteIds.has(id))throw Error('Injected Drive delete failure');assert(files.has(id));files.delete(id);}}},
    ContentService:{MimeType:{JSON:'application/json'},createTextOutput:s=>({text:s,setMimeType(){return this;}})},
    Utilities:{Charset:{UTF_8:'UTF-8'},getUuid:()=>crypto.randomUUID(),newBlob:blob,
      base64Encode:arr=>Buffer.from(arr.map(x=>x&255)).toString('base64'),base64Decode:s=>bytes(Buffer.from(s,'base64')),
      base64EncodeWebSafe:v=>(typeof v==='string'?Buffer.from(v):Buffer.from(v.map(x=>x&255))).toString('base64url'),base64DecodeWebSafe:s=>bytes(Buffer.from(s,'base64url')),
      computeHmacSha256Signature:(s,k)=>bytes(crypto.createHmac('sha256',k).update(s).digest()),
      formatDate:(d,tz,fmt)=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d),get=k=>parts.find(p=>p.type===k).value;return fmt==='yyyy-MM-dd'?`${get('year')}-${get('month')}-${get('day')}`:fmt==='HH:mm'?`${get('hour')}:${get('minute')}`:assert.fail('Unexpected date format');},
      parseCsv:text=>text.trim().split('\n').map(r=>r.split(','))
    }
  });vm.runInContext(code,ctx);ctx.installBackend();
  for(const [role,n] of Object.entries(PHONE))ctx.addUser(n,role,role);
  const config=(k,v)=>{const r=ctx.unique_(ctx.rows_('02_CONFIG'),'clau',k);r.valor=v;ctx.put_('02_CONFIG',r,r._row);};
  const call=p=>clone(JSON.parse(ctx.doPost({postData:{contents:JSON.stringify(p)}}).text));
  const invite=(role='admin')=>clone(ctx.createInviteCore_(PHONE[role],'TEST',ctx.config_()));
  const redeem=(role='admin',codi)=>call({action:'redeemInvite',telefon:PHONE[role],codi,include_bootstrap:true});
  const login=(role='admin')=>{const invitation=invite(role);return redeem(role,invitation.codi);};
  const req=(action,token,extra={})=>call({action,token,request_id:crypto.randomUUID(),...extra});
  const accept=token=>req('acceptPrivacy',token,{accepted:true,version:'1'});
  const session=(role='admin')=>{const r=login(role);assert(r.ok);accept(r.data.token);return r.data.token;};
  const match={partit_id:'P001',jornada:1,data:'2026-10-10',hora:'10:30',local:'CF VILAJUÏGA',visitant:'UE FIGUERES',camp_nom:'Camp de prova',camp_adreca:'',camp_lat:'',camp_lng:'',estat:'pendent',gols_local:'',gols_visitant:'',cronica:'',visible:true,actualitzat_at:'',actualitzat_per:''};ctx.put_('01_PARTITS',match);
  ctx.put_('05_JUGADORS',{jugador_id:'J01',nom:'Prova',dorsal:4,no_mostrar:false,actiu:true});
  // Small marker fixture tests the parser, not a complete JPEG decoder. Full JPEG fixture separately below.
  const jpeg=Buffer.from([255,216,255,192,0,11,8,0,1,0,1,1,1,17,0,255,218,0,8,1,1,0,0,63,0,1,255,217]).toString('base64');
  const upload=(token,extra={})=>req('uploadPhoto',token,{foto_id:crypto.randomUUID(),partit_id:'P001',photo_base64:jpeg,thumb_base64:jpeg,jugadors_ids:['J01'],peu:'',...extra});
  const setUser=(role,values)=>{const u=ctx.unique_(ctx.users_(true),'telefon',PHONE[role]);Object.assign(u,values);ctx.put_('03_USUARIS',u,u._row);ctx.invalidateUsers_();};
  return {ctx,call,req,invite,redeem,login,accept,session,upload,config,properties,cache,sheets,files,folders,failures,setUser,jpeg,metrics,resetMetrics};
}
const tests=[];function test(name,fn){tests.push([name,fn]);}function error(r,code){assert.equal(r.ok,false);assert.equal(r.error.code,code);}
test('installation is repeatable, seven tables, no fake users or fixtures added by installer',()=>{const t=setup();t.ctx.installBackend();assert.equal(t.sheets.size,7);assert.equal(t.ctx.rows_('03_USUARIS').length,3);assert.equal(t.ctx.rows_('01_PARTITS').length,1);});
test('unknown action, malformed JSON, public GET expose no secrets',()=>{const t=setup();error(t.call({action:'addUser'}),'UNKNOWN_ACTION');const r=JSON.parse(t.ctx.doPost({postData:{contents:'{bad'}}).text);error(r,'BAD_JSON');const health=JSON.parse(t.ctx.doGet({parameter:{action:'health'}}).text);assert.equal(health.data.configured,true);assert(!JSON.stringify(health).includes('SESSION_SECRET'));});
test('phone normalisation, unknown and inactive user rejection',()=>{const t=setup();assert.equal(t.ctx.phone_('600 111 222'),PHONE.admin);assert.equal(t.ctx.phone_('0034 600111222'),PHONE.admin);assert.equal(t.ctx.phone_('34600111222'),PHONE.admin);error(t.call({action:'redeemInvite',telefon:'699888777',codi:'1234'}),'INVALID_LOGIN');const invitation=t.invite();t.setUser('admin',{actiu:false});error(t.redeem('admin',invitation.codi),'INVALID_LOGIN');});
test('real Sheet dates and times are normalized before domain use',()=>{const t=setup(),s=t.sheets.get('01_PARTITS'),headers=s.data[0];s.data[1][headers.indexOf('data')]=new Date('2026-10-10T00:00:00Z');s.data[1][headers.indexOf('hora')]=new Date('2026-10-10T08:30:00Z');s.data[1][headers.indexOf('actualitzat_at')]=new Date('2026-10-08T09:12:00Z');const m=t.ctx.rows_('01_PARTITS')[0];assert.equal(m.data,'2026-10-10');assert.equal(m.hora,'10:30');assert.equal(m.actualitzat_at,'2026-10-08T09:12:00.000Z');});
test('malformed and duplicate user rows are ignored without blocking valid families',()=>{const t=setup(),s=t.sheets.get('03_USUARIS'),headers=s.data[0],row=values=>headers.map(key=>values[key]??'');s.data.push(row({telefon:'bad',nom:'Bad',rol:'familia',actiu:true}),row({telefon:PHONE.admin,nom:'Duplicate',rol:'admin',actiu:true}),row({telefon:'+34600999888',nom:'Unknown role',rol:'owner',actiu:true}));assert.equal(t.ctx.users_(true).length,3);assert(t.login().ok);});
test('user migration erases permanent codes and removes obsolete login mode',()=>{const t=setup(),users=t.sheets.get('03_USUARIS'),config=t.sheets.get('02_CONFIG');users.data[0][3]='codi';users.data.slice(1).forEach(row=>row[3]='hmac-v1:legacy');config.data.push(['login_mode','telefon+codi','text','legacy']);t.ctx.installBackend();assert.equal(users.data[0][3],'sessio_epoch');assert(users.data.slice(1).every(row=>row[3]===0));assert.equal(t.ctx.rows_('02_CONFIG').some(row=>row.clau==='login_mode'),false);});
test('privacy gate is enforced at backend, old version rejected',()=>{const t=setup(),r=t.login(),token=r.data.token;error(t.req('bootstrap',token),'PRIVACY_REQUIRED');error(t.req('acceptPrivacy',token,{accepted:false,version:'1'}),'VALIDATION');t.accept(token);assert(t.req('bootstrap',token).ok);t.config('privacy_version','2');error(t.req('bootstrap',token),'PRIVACY_REQUIRED');});
test('token tampering, expiry and future issuance are rejected',()=>{const t=setup(),token=t.session();error(t.req('bootstrap',token+'x'),'UNAUTHORIZED');const [b]=token.split('.'),s=JSON.parse(Buffer.from(b,'base64url'));s.expiresAt=Date.now()-1;let body=Buffer.from(JSON.stringify(s)).toString('base64url');error(t.req('bootstrap',body+'.'+t.ctx.hmac_(body)),'UNAUTHORIZED');s.expiresAt=Date.now()+10000000;s.issuedAt=Date.now()+120000;body=Buffer.from(JSON.stringify(s)).toString('base64url');error(t.req('bootstrap',body+'.'+t.ctx.hmac_(body)),'UNAUTHORIZED');});
test('bootstrap silently renews sessions with less than seven days remaining',()=>{const t=setup(),token=t.session(),[encoded]=token.split('.'),session=JSON.parse(Buffer.from(encoded,'base64url'));session.expiresAt=Date.now()+6*86400000;const body=Buffer.from(JSON.stringify(session)).toString('base64url'),short=body+'.'+t.ctx.hmac_(body),result=t.req('bootstrap',short);assert(result.ok);assert(Date.parse(result.data.renewed.expiresAt)>session.expiresAt);assert(t.req('bootstrap',result.data.renewed.token).ok);});
test('deactivation is immediate for media and writes; logout revokes token',()=>{const t=setup(),token=t.session();t.setUser('admin',{actiu:false});error(t.req('getPhoto',token,{foto_id:crypto.randomUUID()}),'UNAUTHORIZED');t.setUser('admin',{actiu:true});assert(t.req('logout',token).ok);error(t.req('bootstrap',token),'UNAUTHORIZED');});
test('current role and session epoch changes invalidate authority and sessions',()=>{const t=setup(),token=t.session();t.setUser('admin',{rol:'familia'});error(t.req('updateResult',token,{partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:2,gols_visitant:1}),'FORBIDDEN');t.setUser('admin',{rol:'admin',sessio_epoch:1});error(t.req('bootstrap',token),'UNAUTHORIZED');});
test('invite redemption is single-use, generic and never stores the plain code',()=>{const t=setup(),inv=t.invite();assert(t.redeem('admin',inv.codi).ok);const reused=t.redeem('admin',inv.codi);error(reused,'INVALID_LOGIN');const missing=t.call({action:'redeemInvite',telefon:'+34699999999',codi:'0000'}),malformed=t.call({action:'redeemInvite',telefon:'bad',codi:'0000'});error(missing,'INVALID_LOGIN');error(malformed,'INVALID_LOGIN');assert.equal(reused.error.message,missing.error.message);assert.equal(missing.error.message,malformed.error.message);assert(!JSON.stringify(t.ctx.rows_('07_INVITACIONS')).includes(inv.codi));assert(!JSON.stringify(t.ctx.rows_('06_REGISTRE')).includes(inv.codi));});
test('five wrong invite codes burn it and a replacement invite works',()=>{const t=setup(),inv=t.invite();for(let i=0;i<5;i++)error(t.redeem('admin',inv.codi==='0000'?'0001':'0000'),'INVALID_LOGIN');error(t.redeem('admin',inv.codi),'INVALID_LOGIN');assert.equal(t.ctx.rows_('07_INVITACIONS')[0].estat,'cremada');const next=t.invite();assert(t.redeem('admin',next.codi).ok);});
test('new invitations cancel pending codes and expired invitations fail generically',()=>{const t=setup(),old=t.invite(),fresh=t.invite();error(t.redeem('admin',old.codi),'INVALID_LOGIN');assert(t.redeem('admin',fresh.codi).ok);const expired=t.invite('editor'),row=t.ctx.rows_('07_INVITACIONS').find(x=>x.invite_id===expired.invite_id);row.caduca_at='2020-01-01T00:00:00.000Z';t.ctx.put_('07_INVITACIONS',row,row._row);error(t.redeem('editor',expired.codi),'INVALID_LOGIN');assert.equal(t.ctx.rows_('07_INVITACIONS').find(x=>x.invite_id===expired.invite_id).estat,'caducada');});
test('maintenance removes old completed invitations but retains pending ones',()=>{const t=setup(),completed=t.invite(),pending=t.invite('editor');const row=t.ctx.rows_('07_INVITACIONS').find(x=>x.invite_id===completed.invite_id);row.estat='usada';row.creat_at='2020-01-01T00:00:00.000Z';t.ctx.put_('07_INVITACIONS',row,row._row);const pendingRow=t.ctx.rows_('07_INVITACIONS').find(x=>x.invite_id===pending.invite_id);pendingRow.creat_at='2020-01-01T00:00:00.000Z';t.ctx.put_('07_INVITACIONS',pendingRow,pendingRow._row);t.ctx.maintenance();const ids=t.ctx.rows_('07_INVITACIONS').map(x=>x.invite_id);assert(!ids.includes(completed.invite_id));assert(ids.includes(pending.invite_id));});
test('manual log purge removes only entries older than the requested retention',()=>{const t=setup(),token=t.session(),logs=t.ctx.rows_('06_REGISTRE'),old=logs[0];old.timestamp='2020-01-01T00:00:00.000Z';t.ctx.put_('06_REGISTRE',old,old._row);const recent=t.ctx.rows_('06_REGISTRE').at(-1).log_id;t.ctx.purgaRegistre(120);const ids=t.ctx.rows_('06_REGISTRE').map(x=>x.log_id);assert(!ids.includes(old.log_id));assert(ids.includes(recent));assert(t.req('bootstrap',token).ok);});
test('admin-only family actions enforce roles, active users and last-admin safety',()=>{const t=setup(),family=t.session('familia'),admin=t.session();for(const action of ['createInvite','saveUser','revokeSessions'])error(t.req(action,family,{telefon:PHONE.editor,nom:'Editor',rol:'editor'}),'FORBIDDEN');error(t.req('listUsers',family),'FORBIDDEN');error(t.req('createInvite',admin,{telefon:'+34699999999'}),'NOT_FOUND');error(t.req('saveUser',admin,{telefon:PHONE.admin,nom:'Admin',rol:'familia',actiu:true}),'VALIDATION');assert(t.req('saveUser',admin,{telefon:'+34600444555',nom:'Nova família',rol:'familia',actiu:true}).ok);assert(t.req('listUsers',admin).data.usuaris.some(x=>x.telefon==='+34600444555'));});
test('two invite sessions coexist until admin revokes all with session epoch',()=>{const t=setup(),first=t.session('editor'),second=t.session('editor'),admin=t.session();assert(t.req('bootstrap',first).ok);assert(t.req('bootstrap',second).ok);assert(t.req('revokeSessions',admin,{telefon:PHONE.editor}).ok);error(t.req('bootstrap',first),'UNAUTHORIZED');error(t.req('bootstrap',second),'UNAUTHORIZED');});
test('deactivation cancels pending invitations and prevents old sessions reviving',()=>{const t=setup(),editor=t.session('editor'),pending=t.invite('editor'),admin=t.session();assert(t.req('saveUser',admin,{telefon:PHONE.editor,nom:'editor',rol:'editor',actiu:false}).ok);error(t.req('bootstrap',editor),'UNAUTHORIZED');error(t.redeem('editor',pending.codi),'INVALID_LOGIN');assert(t.req('saveUser',admin,{telefon:PHONE.editor,nom:'editor',rol:'editor',actiu:true}).ok);error(t.req('bootstrap',editor),'UNAUTHORIZED');});
test('privacy acceptance retry does not duplicate audit',()=>{const t=setup(),r=t.login(),token=r.data.token,id=crypto.randomUUID();assert(t.req('acceptPrivacy',token,{request_id:id,accepted:true,version:'1'}).ok);assert(t.req('acceptPrivacy',token,{request_id:id,accepted:true,version:'1'}).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='ACCEPT_PRIVACY').length,1);});
test('results: permission, type validation, optimistic conflict and retry',()=>{const t=setup(),token=t.session('editor'),payload={partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:3,gols_visitant:2,request_id:crypto.randomUUID()};error(t.req('updateResult',token,{...payload,gols_local:'3'}),'VALIDATION');const r=t.req('updateResult',token,payload);assert(r.ok);assert(t.req('updateResult',token,payload).data.replayed);error(t.req('updateResult',token,{...payload,request_id:crypto.randomUUID()}),'CONFLICT');assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_RESULT').length,1);});
test('chronicle text starting with formula is stored literally; bootstrap has no private phones',()=>{const t=setup(),token=t.session('editor');assert(t.req('updateChronicle',token,{partit_id:'P001',expected_updated_at:'',cronica:'=IMPORTXML("secret")'}).ok);assert.equal(t.ctx.rows_('01_PARTITS')[0].cronica,'=IMPORTXML("secret")');const data=t.req('bootstrap',token).data;assert(!JSON.stringify(data).includes(PHONE.editor));assert(!JSON.stringify(data).includes('hmac-v1'));});
test('stats home/away, draws and non-team fixtures',()=>{const t=setup();const c=t.ctx.config_(),base=t.ctx.rows_('01_PARTITS')[0];const s=t.ctx.statistics_([{...base,estat:'jugat',gols_local:3,gols_visitant:2},{...base,local:'Other',visitant:c.equip_nom,estat:'jugat',gols_local:0,gols_visitant:2},{...base,estat:'jugat',gols_local:1,gols_visitant:1},{...base,local:'X',visitant:'Y',estat:'jugat',gols_local:9,gols_visitant:0}],c);assert.deepEqual(clone(s),{PJ:3,V:2,E:1,D:0,GF:6,GC:3,DG:3});});
test('family upload idempotent with same photo_id, no Drive IDs or uploader phone exposed',()=>{const t=setup(),token=t.session('familia'),id=crypto.randomUUID();const r=t.upload(token,{foto_id:id});assert(r.ok);assert(!JSON.stringify(r).includes('drive_file_id'));assert(!JSON.stringify(r).includes(PHONE.familia));const again=t.upload(token,{foto_id:id});assert(again.data.replayed);assert.equal(t.ctx.rows_('04_FOTOS').length,1);assert.equal([...t.files.values()].filter(f=>f.mime!=='application/vnd.google-apps.spreadsheet').length,2);});
test('uploads require player tags or an explicit no-identifiable-player confirmation',()=>{const t=setup(),token=t.session('familia');error(t.upload(token,{jugadors_ids:[],sense_jugadors:false}),'VALIDATION');assert(t.upload(token,{jugadors_ids:[],sense_jugadors:true}).ok);});
test('JPEG validation rejects oversized, invalid dimensions, malformed base64 and GPS metadata',()=>{const t=setup(),token=t.session();error(t.upload(token,{photo_base64:'bad'}),'VALIDATION');let b=Buffer.from(t.jpeg,'base64');b[9]=7;b[10]=208;error(t.upload(token,{photo_base64:b.toString('base64')}),'VALIDATION');const exif=Buffer.concat([Buffer.from([255,216,255,225,0,4,1,2]),Buffer.from(t.jpeg,'base64').subarray(2)]);error(t.upload(token,{photo_base64:exif.toString('base64')}),'VALIDATION');error(t.call({action:'uploadPhoto',padding:'x'.repeat(2400001)}),'PAYLOAD_TOO_LARGE');});
test('upload cleans first file if thumbnail creation fails',()=>{const t=setup(),token=t.session();t.failures.createAt=2;error(t.upload(token),'INTERNAL_ERROR');assert.equal(t.ctx.rows_('04_FOTOS').length,0);assert.equal(t.files.size,1);});
test('upload whose audit failed can recover without duplicating photo files',()=>{const t=setup(),token=t.session(),id=crypto.randomUUID(),request_id=crypto.randomUUID();t.failures.writeName='06_REGISTRE';error(t.upload(token,{foto_id:id,request_id}),'INTERNAL_ERROR');assert.equal(t.ctx.rows_('04_FOTOS').length,1);t.failures.writeName=null;assert(t.upload(token,{foto_id:id,request_id}).ok);assert.equal(t.files.size,3);});
test('hidden photo, player restriction and blank privacy flag block normal retrieval',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),r=t.upload(admin),id=r.data.foto.foto_id;assert(t.req('getPhoto',family,{foto_id:id}).ok);const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);error(t.req('getPhoto',family,{foto_id:id,include_hidden:true}),'NOT_FOUND');error(t.req('getPhoto',admin,{foto_id:id}),'NOT_FOUND');assert(t.req('getPhoto',admin,{foto_id:id,include_hidden:true}).ok);assert.equal(t.req('listPhotos',family,{partit_id:'P001'}).data.fotos.length,0);j.no_mostrar='';t.ctx.put_('05_JUGADORS',j,j._row);error(t.req('getPhoto',family,{foto_id:id}),'NOT_FOUND');});
test('SHOW_PHOTO does not bypass a blocked player, family cannot hide/delete',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),id=t.upload(admin).data.foto.foto_id;error(t.req('hidePhoto',family,{foto_id:id}),'FORBIDDEN');assert(t.req('hidePhoto',admin,{foto_id:id,motiu:'Privacitat'}).ok);error(t.req('getPhoto',family,{foto_id:id}),'NOT_FOUND');const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);assert(t.req('showPhoto',admin,{foto_id:id}).data.foto.bloquejada);error(t.req('getPhoto',family,{foto_id:id}),'NOT_FOUND');error(t.req('deletePhoto',family,{foto_id:id,confirm_permanent:true}),'FORBIDDEN');});
test('private file parent, name and sharing are checked, arbitrary Drive ID ignored',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id,f=t.ctx.rows_('04_FOTOS')[0],file=t.files.get(f.drive_file_id);file.shared=true;error(t.req('getPhoto',token,{foto_id:id}),'DRIVE_NOT_PRIVATE');file.shared=false;file.name='different.jpg';error(t.req('getPhoto',token,{foto_id:id}),'NOT_FOUND');error(t.req('getPhoto',token,{foto_id:crypto.randomUUID(),drive_file_id:f.drive_file_id}),'NOT_FOUND');});
test('download ack required, audit always records initiated downloads, retries deduplicated',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id;error(t.req('downloadPhoto',token,{foto_id:id}),'VALIDATION');const request_id=crypto.randomUUID();assert(t.req('downloadPhoto',token,{foto_id:id,private_use_ack:true,request_id}).ok);assert(t.req('downloadPhoto',token,{foto_id:id,private_use_ack:true,request_id}).ok);assert(t.req('downloadPhoto',token,{foto_id:id,private_use_ack:true}).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='DOWNLOAD_PHOTO').length,2);});
test('thumbnail batches capped at six and individually hide forbidden items',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),id=t.upload(admin).data.foto.foto_id;error(t.req('getThumbnails',family,{foto_ids:Array.from({length:7},()=>crypto.randomUUID())}),'VALIDATION');const r=t.req('getThumbnails',family,{foto_ids:[id,crypto.randomUUID()]});assert(r.ok);assert(r.data.items[0].ok);assert.equal(r.data.items[1].error.code,'NOT_FOUND');});
test('partial deletion tombstones photo, retries finish remaining files, confirmation required',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id,f=t.ctx.rows_('04_FOTOS')[0],request_id=crypto.randomUUID();error(t.req('deletePhoto',token,{foto_id:id}),'VALIDATION');t.failures.deleteIds.add(f.thumb_file_id);const r=t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true,request_id});assert(r.data.pending);error(t.req('getPhoto',token,{foto_id:id,include_hidden:true}),'NOT_FOUND');t.failures.deleteIds.clear();assert(t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true,request_id}).data.permanent);assert.equal(t.files.size,1);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='DELETE_PHOTO_COMPLETE').length,1);assert(t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true,request_id}).data.deleted);});
test('missing Drive file is reported pending rather than falsely claiming permanent deletion',()=>{const t=setup(),token=t.session(),id=t.upload(token).data.foto.foto_id,f=t.ctx.rows_('04_FOTOS')[0];t.files.delete(f.drive_file_id);const r=t.req('deletePhoto',token,{foto_id:id,confirm_permanent:true});assert(r.data.pending);assert.equal(r.data.deleted,false);});
test('corrupt headers and duplicate IDs fail closed',()=>{const t=setup(),inv=t.invite();t.sheets.get('03_USUARIS').data[0][0]='bad';error(t.redeem('admin',inv.codi),'SCHEMA_ERROR');});
test('calendar invalid row rejects entire import before any writes',()=>{const t=setup(),csv='partit_id,jornada,data,hora,local,visitant,camp_nom,camp_adreca,camp_lat,camp_lng\nP002,2,2026-10-17,12:00,CF VILAJUÏGA,Other,Camp,,,\nP003,3,2026-02-30,12:00,CF VILAJUÏGA,Other,Camp,,,';assert.throws(()=>t.ctx.importCalendar(csv));assert.equal(t.ctx.rows_('01_PARTITS').length,1);});
test('result journal recovers failed audit and blocks competing edits until retry',()=>{const t=setup(),token=t.session('editor'),payload={partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:4,gols_visitant:0,request_id:crypto.randomUUID()};t.failures.writeName='06_REGISTRE';error(t.req('updateResult',token,payload),'INTERNAL_ERROR');assert.equal(t.ctx.rows_('01_PARTITS')[0].gols_local,4);assert(t.properties.has('pendingMatch:P001'));t.failures.writeName=null;error(t.req('updateChronicle',token,{partit_id:'P001',expected_updated_at:t.ctx.rows_('01_PARTITS')[0].actualitzat_at,cronica:'New'}),'BUSY');assert(t.req('updateResult',token,payload).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_RESULT').length,1);assert(!t.properties.has('pendingMatch:P001'));});
test('editor-only recovery completes already applied update audit after lost session',()=>{const t=setup(),token=t.session('editor');t.failures.writeName='06_REGISTRE';error(t.req('updateChronicle',token,{partit_id:'P001',expected_updated_at:'',cronica:'Updated',request_id:crypto.randomUUID()}),'INTERNAL_ERROR');t.failures.writeName=null;const r=t.ctx.recoverPendingMatchAudits();assert.equal(r[0].status,'audited');assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_CHRONICLE').length,1);assert(!t.properties.has('pendingMatch:P001'));});
test('failed match write leaves journal, same request commits once after retry',()=>{const t=setup(),token=t.session('editor'),payload={partit_id:'P001',expected_updated_at:'',estat:'jugat',gols_local:1,gols_visitant:1,request_id:crypto.randomUUID()};t.failures.writeName='01_PARTITS';error(t.req('updateResult',token,payload),'INTERNAL_ERROR');t.failures.writeName=null;assert(t.req('updateResult',token,payload).ok);assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='UPDATE_RESULT').length,1);});
test('real canvas-compatible JPEG passes size and dimension parser',()=>{const t=setup(),j=t.ctx.jpeg_('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBAUEBAYFBQUGBgYHCQ4JCQgICRINDQoOFRIWFhUSFBQXGiEcFxgfGRQUHScdHyIjJSUlFhwpLCgkKyEkJST/2wBDAQYGBgkICREJCREkGBQYJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCT/wAARCAADAAIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDy+iiivOPnj//Z',1572864,1600);assert.equal(j.width,2);assert.equal(j.height,3);});

function playerPayload(t,extra={}){return {jugador_id:'J01',nom:'Prova',dorsal:4,posicio:'Migcampista',expected_updated_at:'',...extra};}
test('player schema upgrade preserves original columns and data, refuses conflicting header',()=>{const t=setup(),s=t.sheets.get('05_JUGADORS');s.data[0]=s.data[0].slice(0,5);t.ctx.installBackend();assert.equal(s.data[0].length,11);assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Prova');s.data[0][5]='personal';assert.throws(()=>t.ctx.installBackend());});
test('only admin can save player cards; restricted flags are preserved',()=>{const t=setup(),family=t.session('familia'),admin=t.session();error(t.req('savePlayer',family,playerPayload(t)),'FORBIDDEN');const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);const r=t.req('savePlayer',admin,playerPayload(t,{nom:'Nou nom',no_mostrar:false}));assert(r.ok);assert.equal(r.data.jugador.no_mostrar,true);assert.equal(t.req('bootstrap',family).data.jugadors.length,0);});
test('player portrait save, permissions, private folder and bootstrap omit Drive IDs',()=>{const t=setup(),admin=t.session(),family=t.session('familia'),r=t.req('savePlayer',admin,playerPayload(t,{photo_base64:t.jpeg,foto_id:crypto.randomUUID()}));assert(r.ok);assert(r.data.jugador.te_retrat);assert(!JSON.stringify(r).includes('foto_drive_file_id'));const b=t.req('bootstrap',family).data;assert(b.features.player_cards);assert.equal(b.jugadors[0].posicio,'Migcampista');assert(!JSON.stringify(b).includes('foto_drive_file_id'));const media=t.req('getPlayerPortraits',family,{jugador_ids:['J01']});assert(media.data.items[0].ok);assert.equal(media.data.items[0].base64,t.jpeg);const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);assert(!t.req('getPlayerPortraits',family,{jugador_ids:['J01'],include_hidden:true}).data.items[0].ok);assert(!t.req('getPlayerPortraits',admin,{jugador_ids:['J01']}).data.items[0].ok);assert(t.req('getPlayerPortraits',admin,{jugador_ids:['J01'],include_hidden:true}).data.items[0].ok);});
test('portrait ID, folder, file name and sharing are verified on every read',()=>{const t=setup(),admin=t.session();t.req('savePlayer',admin,playerPayload(t,{photo_base64:t.jpeg,foto_id:crypto.randomUUID()}));const j=t.ctx.rows_('05_JUGADORS')[0],file=t.files.get(j.foto_drive_file_id);file.shared=true;assert.equal(t.req('getPlayerPortraits',admin,{jugador_ids:['J01']}).data.items[0].error.code,'DRIVE_NOT_PRIVATE');file.shared=false;file.viewers.push('unexpected-viewer');assert.equal(t.req('getPlayerPortraits',admin,{jugador_ids:['J01']}).data.items[0].error.code,'DRIVE_NOT_PRIVATE');file.viewers=[];file.name='wrong.jpg';assert(!t.req('getPlayerPortraits',admin,{jugador_ids:['J01'],drive_file_id:j.foto_drive_file_id}).data.items[0].ok);error(t.req('getPlayerPortraits',admin,{jugador_ids:Array.from({length:7},(_,i)=>'J'+i)}),'VALIDATION');});
test('player save retries recover failed audit without duplicating portrait, reject altered request',()=>{const t=setup(),admin=t.session(),request_id=crypto.randomUUID(),p=playerPayload(t,{request_id,photo_base64:t.jpeg,foto_id:crypto.randomUUID()});t.failures.writeName='06_REGISTRE';error(t.req('savePlayer',admin,p),'INTERNAL_ERROR');const files=t.files.size;t.failures.writeName=null;assert(t.req('savePlayer',admin,p).data.replayed);assert.equal(t.files.size,files);error(t.req('savePlayer',admin,{...p,nom:'Changed'}),'CONFLICT');assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='SAVE_PLAYER').length,1);error(t.req('savePlayer',admin,playerPayload(t)),'CONFLICT');});
test('failed player row write cleans newly created portrait; original player is intact',()=>{const t=setup(),admin=t.session(),files=t.files.size;t.failures.writeName='05_JUGADORS';error(t.req('savePlayer',admin,playerPayload(t,{photo_base64:t.jpeg,foto_id:crypto.randomUUID()})),'INTERNAL_ERROR');assert.equal(t.files.size,files);assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Prova');});
test('new player card gets active flag and escaped formula-safe name; invalid fields rejected',()=>{const t=setup(),admin=t.session();error(t.req('savePlayer',admin,playerPayload(t,{dorsal:100})),'VALIDATION');error(t.req('savePlayer',admin,playerPayload(t,{posicio:'Unknown'})),'VALIDATION');error(t.req('savePlayer',admin,playerPayload(t,{photo_base64:'bad',foto_id:crypto.randomUUID()})),'VALIDATION');const r=t.req('savePlayer',admin,playerPayload(t,{jugador_id:'J02',nom:'=PROVA',dorsal:''}));assert(r.ok);assert.equal(t.ctx.rows_('05_JUGADORS')[1].nom,'=PROVA');assert.equal(t.ctx.rows_('05_JUGADORS')[1].actiu,true);});
test('six thumbnails read each table once and reuse the validated parent folder',()=>{
  const t=setup(),token=t.session('familia'),ids=Array.from({length:6},()=>t.upload(token).data.foto.foto_id);
  t.resetMetrics();const result=t.req('getThumbnails',token,{foto_ids:ids});
  assert(result.ok);assert.equal(result.data.items.filter(x=>x.ok).length,6);
  assert.equal(t.metrics.spreadsheetOpens,1);
  assert(Object.values(t.metrics.tableReads).every(n=>n===1));
  assert(Object.values(t.metrics.headerReads).every(n=>n===1));assert.equal(t.metrics.folderLookups,1);
  assert.equal(t.metrics.advancedFileReads,6);assert.equal(t.metrics.metadataReads,0);assert.equal(t.metrics.parentReads,0);
  // A later request must see manual restrictions, changed sharing and changed headers.
  const j=t.ctx.rows_('05_JUGADORS')[0];j.no_mostrar=true;t.ctx.put_('05_JUGADORS',j,j._row);
  assert(t.req('getThumbnails',token,{foto_ids:ids}).data.items.every(x=>!x.ok));
  j.no_mostrar=false;t.ctx.put_('05_JUGADORS',j,j._row);
  const f=t.ctx.rows_('04_FOTOS')[0],folder=t.files.get(f.thumb_file_id).folder;folder.shared=true;
  assert(t.req('getThumbnails',token,{foto_ids:ids}).data.items.every(x=>!x.ok));folder.shared=false;
  t.sheets.get('04_FOTOS').data[0][0]='incorrect';
  assert(t.req('getThumbnails',token,{foto_ids:ids}).data.items.every(x=>!x.ok));
});
test('combined invite redemption and consent bootstrap never expose data before current acceptance',()=>{
  const t=setup(),first=t.invite(),r=t.call({action:'redeemInvite',telefon:PHONE.admin,codi:first.codi,include_bootstrap:true});
  assert(r.ok);assert.equal(r.data.bootstrap,undefined);
  const token=r.data.token,request_id=crypto.randomUUID();
  error(t.req('acceptPrivacy',token,{accepted:true,version:'0',include_bootstrap:true}),'VALIDATION');
  const accepted=t.req('acceptPrivacy',token,{request_id,accepted:true,version:'1',include_bootstrap:true});
  assert(accepted.data.bootstrap.features.fresh_permissions);assert.equal(accepted.data.bootstrap.partits.length,1);
  const retry=t.req('acceptPrivacy',token,{request_id,accepted:true,version:'1',include_bootstrap:true});assert(retry.data.bootstrap.user.privacyAccepted);
  assert.equal(t.ctx.rows_('06_REGISTRE').filter(x=>x.accio==='ACCEPT_PRIVACY').length,1);
  const nextInvite=t.invite(),next=t.call({action:'redeemInvite',telefon:PHONE.admin,codi:nextInvite.codi,include_bootstrap:true});assert(next.data.bootstrap.user.privacyAccepted);
  const oldInvite=t.invite(),old=t.call({action:'redeemInvite',telefon:PHONE.admin,codi:oldInvite.codi});assert.equal(old.data.bootstrap,undefined,'clients without combined bootstrap retain the original response');
  t.config('privacy_version','2');const changed=t.invite();assert.equal(t.call({action:'redeemInvite',telefon:PHONE.admin,codi:changed.codi,include_bootstrap:true}).data.bootstrap,undefined);
});
test('an empty gallery avoids reading players and supports privacy-safe diagnostics',()=>{
  const t=setup(),token=t.session('familia');t.resetMetrics();
  const result=t.req('listPhotos',token,{partit_id:'P001',diagnostics:true});
  assert(result.ok);assert.deepEqual(result.data.fotos,[]);
  assert.equal(t.metrics.tableReads['05_JUGADORS']||0,0);assert.equal(t.metrics.headerReads['05_JUGADORS']||0,0);
  assert(Number.isInteger(result.data.diagnostics.server_ms));assert(result.data.diagnostics.server_ms>=0);
  assert(!JSON.stringify(result.data.diagnostics).includes(PHONE.familia));assert(!JSON.stringify(result.data.diagnostics).includes(token));
});
test('bootstrap does not reuse a previous user cache after manual role or activation changes',()=>{
  const t=setup(),token=t.session();assert(t.req('bootstrap',token).data.features.fresh_permissions);
  // Simulate direct Sheet editing without calling invalidateUsers_.
  const s=t.sheets.get('03_USUARIS');s.data[1][2]='familia';
  assert.equal(t.req('bootstrap',token).data.user.rol,'familia');
  s.data[1][4]=false;error(t.req('bootstrap',token),'UNAUTHORIZED');
});
test('request snapshots isolate unsaved edits, reflect writes, and are discarded after failure',()=>{
  const t=setup();
  t.ctx.inRequest_(()=>{
    const j=t.ctx.rows_('05_JUGADORS')[0];j.nom='Unsaved';
    assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Prova');
    t.ctx.put_('05_JUGADORS',j,j._row);assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Unsaved');
  });
  assert.throws(()=>t.ctx.inRequest_(()=>{t.ctx.rows_('05_JUGADORS');throw Error('Injected');}));
  t.sheets.get('05_JUGADORS').data[1][1]='Manual change';
  assert.equal(t.ctx.rows_('05_JUGADORS')[0].nom,'Manual change');
});
module.exports={setup,PHONE};
if(require.main===module){
let passed=0;for(const [name,fn]of tests){try{fn();console.log('PASS '+name);passed++;}catch(e){console.error('FAIL '+name+'\n'+e.stack);process.exitCode=1;}}
console.log(`${passed}/${tests.length} passed`);

}
